
CREATE TABLE IF NOT EXISTS irunaitem
    (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'Absorbant Gel','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Abyss Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Accuracy Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Aconitum','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Acrobat Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Actsin Guard','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Acupuncture bandage','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Adamantite Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Aegis Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Agility Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Agira Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Alchemy Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Aldi''s Coin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Alloy Cross','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Alloy Pentagram','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ancient Artifact','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Anga''s Coin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Angel Arrow','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Angel brooch','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Angel Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Anti-Magic Armor','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Anti-Melee Armor','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Archer glove','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Archon Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Argent Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Arrogant Dragon Fang','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Arrogant Dragon Fang Art','Special');
INSERT INTO `irunaitem` VALUES(NULL,'assassin''s ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Atleta Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Attack Buckle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Auto Revita','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Autumn Leave Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Azuki Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Bamboo Talisman','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Barrier Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Battered Boots','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Battered Carving','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Battery','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Beam Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Big Volcano Stone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Crystal Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Bone Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Boost Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Bracelet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brass Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brass Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brass Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brass Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brass Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brave Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Breeze Brooch','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brille Earrings','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Brilliant Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Broken Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Bud Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Burning Oxcart','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Calm Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Calming Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Canon Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Caravan Soldier Belt','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Carpentry Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Carved Demon','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cat Forepaws','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Catura Talisman','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cave Indigo','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Chakram Gauntlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Chaotic Hourglass','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Charge Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Charm of Sofys','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Chasing Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Chief God''s Stone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Circle of Life','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Claw Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Claw Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Claw Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Colon Badge','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Conch Shell','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cooking Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cool Breeze','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Copper Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Copper Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Copper Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Copper Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Copper Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Coral Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Coral Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cotton cloud','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Counter Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Craft Guide Book','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Critical Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Critical Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Crystal Claw','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Crystal Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cursed Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cursed Horseshoe','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Cutter Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Damascan Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Devil Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Goddess'' Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Hunter Eye','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Death Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Decoration Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Deep Forest Cave','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Deep Snow Ice Pillar','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dexterity Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Diamond Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Diel Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Disaster Stone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Discharge Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dodge Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dodge Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Douin''s Feathers','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Douin''s Talisman','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dracula Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Doll','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Fang Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Rosary','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dragonewt Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dusk Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Dusk Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Devil Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Earth God''s Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Elban Badge','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Elemental Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Elemental Wristlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Endurance Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Engraved Powder Case','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Evil Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Executioner Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Faithful Knight Soul','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Falte Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fate Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fearsome Claw','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Festan Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fine Carving','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fire Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fire Devil Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fire God''s Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fire Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fish-Scale Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fish-Scale Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Flaring Sun','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Flash Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Floral Perfume','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fluffy Mittens','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Forest Bead','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Forest Spirit','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fortitude Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fortune-telling Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fossil Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Fox Tail','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Friend Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Friend Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Frog Sword','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gaiety Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Garel Engine','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gate Pass','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gaudy Bracelet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gauntlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gauntlet+','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Geo Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ghost Candle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gigante Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Glass Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Glass Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Glint Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Cross','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Star','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Golem Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Good Luck Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Grass Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Boots','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Green Water Crystal','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ground Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Guard Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Guard''s Badge','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Hard Scale Claw','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Heal Pendant','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Heavy Boots','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Hell Money','Special');
INSERT INTO `irunaitem` VALUES(NULL,'hero bandage','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Hero Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'hero staff','Special');
INSERT INTO `irunaitem` VALUES(NULL,'hero sword sheath','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Hero Talisman','Special');
INSERT INTO `irunaitem` VALUES(NULL,'hero throwing gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'heroic archer''s quiver','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Horn Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Horn Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Hornet Earrings','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Hunter Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Hunter Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Crystal Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Immovable Stone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Inferno Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Inothi Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Intelligence Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Tsuba','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Jack Bracelet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Jar of Greed','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Javali Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Killer Seed','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Knight Gauntlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Knight Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ku Holin Medal','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Leafy Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Leafy Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Leather gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Light Devil Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Light God''s Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Light Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Lily Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Little Fang Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Lotus Petal','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Lotus Seeds','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Love Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Lowell Wristband','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Luna''s Swim Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Luster Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Amp','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Magical Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Martial Arts Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mason Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Master''s Jittoku Tool','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Medical Book','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Medical Book II','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Medical Book III','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Medical Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mermaid Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mermaid Jewel','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Merman Gem','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Metal Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Metallic Black Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Metallophone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Might Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mighty Boots','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Miner Towel','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mio''s Sword Strap','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mirage Stone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'mirror piece','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mithril Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Monkey Tail','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mononofu Gauntlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Moss-grown Pot','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Muscle Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Musie''s Coin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Myrica Wristlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mystic Arrow','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Cross','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Loop','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Star','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Natural Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Nature Arrow','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Necklace of Mortification','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Nervure Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'New High-Speed Motor','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Nightscore','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ninja Gauntlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Normal Carving','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Noshime','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Null Stone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Nyme Medal','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Old Bone Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Old Jittoku Tool','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ominous Doll','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orc Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Cross','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Hexagram','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Orichalcum Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Outrage Nail','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Owl Feather','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Pandora Box','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Parul Caravan Book','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Pex Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Phantom Coat','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Piton Strap','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Cross','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Star','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Pole''s Harp','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Pole''s Talisman','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Power Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Powerful Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'pressure sensitive acceleration AI','Special');
INSERT INTO `irunaitem` VALUES(NULL,'pressure sensitive defence AI','Special');
INSERT INTO `irunaitem` VALUES(NULL,'pressure sensitive reinforcement AI','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Pretty Bouquet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Production Book','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Proof of Sentry','Special');
INSERT INTO `irunaitem` VALUES(NULL,'PTA President''s Seal','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Pure Water Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Pure White Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Purple Crystal Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Quake Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Quick Gauntlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Raptor Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Recovery Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Red Mountain Fire Ore','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Reduce Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Reflect Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Regera Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Regera Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'reiki','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Resist Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Resolve Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Retile Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Revita Pouch','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Revival Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Bond','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Calm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Darkness','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Earthquake','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Fall','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Frost','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Fury','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Illusion','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Inferno','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Light','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Rush','Special');
INSERT INTO `irunaitem` VALUES(NULL,'ring of soul','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Storm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ring of Tide','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Rings of Easter','Special');
INSERT INTO `irunaitem` VALUES(NULL,'rock of big lake','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Rose Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Rusted Bronze Coin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Rustling Leaf Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sacred Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Safety Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sage Emblem','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sake Ladle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sakura Branch','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sakura Petal','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Samurai Tasuki','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sand Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Santa Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Scholar Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Scissors','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Scout Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Seahorse Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Secret Production Book','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Seven Mile Boots','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Shackle of Depression','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Shell Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Shellfish Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Shock Absorber','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Shoryouma','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Showy Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silk Mittens','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Cross','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Hairpin','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Star','Special');
INSERT INTO `irunaitem` VALUES(NULL,'skeleton debris','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Skill Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Skyblue Choker','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Slebinian Badge','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Slump Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Smithing Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Snakeskin Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Soldier Badge','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Solid Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sorcery Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Soul Sucker Fang','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Space Debris','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Specia''s Blessed Stone','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Buckle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spell King''s Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spellsword Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spiked Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spiked Gauntlet','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spina Pouch','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spirit Statue','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Spiritual Balm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Stamina Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Star Fang Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Star Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'stardust fluorite','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Stardust Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Staring Evil Eye','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Stem Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Stingy Eye','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Stone Maze Clod','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Storm Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Strategy Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Stream Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Strength Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Suishin''s Kozuka','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Sunshine Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Superhero Badge','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Swordsman Medal','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Swordsman''s petite','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Tailoring Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Taktstock','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Talisman Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Taunt Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Tempest Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ten Mile Boots','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Tenacity Glove','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Thimble','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Thrift Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Ticheli Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Tigle Shoes','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Tilia''s Talisman','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Toughness Buckle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Toughness Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Traveler Gloves','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Traveler''s Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Turia Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Twisted Hachimaki','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Unadorned Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Undying Torch','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Unmelting Ice','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Vigor Emblem','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Violet Soul','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Vital Scarf','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Vitality Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Volk Shoes','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Volt Orb','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Warm Scarf','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Warped Stone Figurine','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Warrior Bangle','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wasteland Spring Water','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Water Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Water Devil Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Water Goddess'' Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Water Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Weakness Finder','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Weakness Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Weasel Cylinder','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wedding Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Welling Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'White Corsage','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wild Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Will to Live','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Arrows','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Devil Necklace','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Fan','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Goddess'' Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wind-up Doll','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wisdom Earring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wisdom Page','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wisdom Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wise Man''s Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wit Charm','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Witch''s Curse Ring','Special');
INSERT INTO `irunaitem` VALUES(NULL,'Wood Hammer','Special');
COMMIT;
