
CREATE TABLE irunaitem
             (name text, category text);
INSERT INTO `irunaitem` VALUES('Antidote    ','Status');
INSERT INTO `irunaitem` VALUES('Chana Masala    ','Status');
INSERT INTO `irunaitem` VALUES('Coagulant    ','Status');
INSERT INTO `irunaitem` VALUES('Cure Paralysis    ','Status');
INSERT INTO `irunaitem` VALUES('Energy Herb    ','Status');
INSERT INTO `irunaitem` VALUES('Eye Drops    ','Status');
INSERT INTO `irunaitem` VALUES('Mapo Dofu    ','Status');
INSERT INTO `irunaitem` VALUES('Merry Sweets    ','Status');
INSERT INTO `irunaitem` VALUES('Mikan Daifuku    ','Status');
INSERT INTO `irunaitem` VALUES('Moist Dirt    ','Status');
INSERT INTO `irunaitem` VALUES('Moss Manju    ','Status');
INSERT INTO `irunaitem` VALUES('Sirok    ','Status');
INSERT INTO `irunaitem` VALUES('Soybean Paste Soup    ','Status');
INSERT INTO `irunaitem` VALUES('Spice    ','Status');
INSERT INTO `irunaitem` VALUES('Spinnen Vaccine    ','Status');
INSERT INTO `irunaitem` VALUES('Stimulant    ','Status');
INSERT INTO `irunaitem` VALUES('Super Vaccine    ','Status');
INSERT INTO `irunaitem` VALUES('Tandoori Chicken    ','Status');
INSERT INTO `irunaitem` VALUES('Tear of the Moon    ','Status');
INSERT INTO `irunaitem` VALUES('Tranquilizer    ','Status');
INSERT INTO `irunaitem` VALUES('Trial Vaccine    ','Status');
INSERT INTO `irunaitem` VALUES('Tvorog    ','Status');
INSERT INTO `irunaitem` VALUES('Unread Fortune    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Bleed)    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Blind)    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Dizzy)    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Fear)    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Freeze)    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Lethargy)    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Paral.)    ','Status');
INSERT INTO `irunaitem` VALUES('Vaccine (Poison)    ','Status');
INSERT INTO `irunaitem` VALUES('Aged Revita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Anko    ','Recovery');
INSERT INTO `irunaitem` VALUES('Apple    ','Recovery');
INSERT INTO `irunaitem` VALUES('Apple Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Bad Apple    ','Recovery');
INSERT INTO `irunaitem` VALUES('Bad Watermelon    ','Recovery');
INSERT INTO `irunaitem` VALUES('Bamboo Bottle    ','Recovery');
INSERT INTO `irunaitem` VALUES('Banana    ','Recovery');
INSERT INTO `irunaitem` VALUES('Banana au Lait    ','Recovery');
INSERT INTO `irunaitem` VALUES('Banana Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Basmati Rice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Bat Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Bean Curd    ','Recovery');
INSERT INTO `irunaitem` VALUES('Beautiful Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Beef    ','Recovery');
INSERT INTO `irunaitem` VALUES('Big Egg    ','Recovery');
INSERT INTO `irunaitem` VALUES('Big Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Binal (L)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Binal (M)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Binal (S)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Binal (XL)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Binal (XXL)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Black Bandage    ','Recovery');
INSERT INTO `irunaitem` VALUES('Black Gel Drink    ','Recovery');
INSERT INTO `irunaitem` VALUES('Black Jelly    ','Recovery');
INSERT INTO `irunaitem` VALUES('Blind Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Blue Gel Drink    ','Recovery');
INSERT INTO `irunaitem` VALUES('Blue Jelly    ','Recovery');
INSERT INTO `irunaitem` VALUES('Blue Mushroom    ','Recovery');
INSERT INTO `irunaitem` VALUES('Boar Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Boat prime    ','Recovery');
INSERT INTO `irunaitem` VALUES('Boat-Wrap Sashimi    ','Recovery');
INSERT INTO `irunaitem` VALUES('Bread    ','Recovery');
INSERT INTO `irunaitem` VALUES('Bright Cacao    ','Recovery');
INSERT INTO `irunaitem` VALUES('Burnt Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Butter    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cacao    ','Recovery');
INSERT INTO `irunaitem` VALUES('Candy    ','Recovery');
INSERT INTO `irunaitem` VALUES('Candy Apple    ','Recovery');
INSERT INTO `irunaitem` VALUES('Candy Syrup    ','Recovery');
INSERT INTO `irunaitem` VALUES('Caozaiguo    ','Recovery');
INSERT INTO `irunaitem` VALUES('Carrot    ','Recovery');
INSERT INTO `irunaitem` VALUES('Century Egg    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cheese    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cherry    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cherry Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cherry Pie    ','Recovery');
INSERT INTO `irunaitem` VALUES('Chicken Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Chicken Nanban    ','Recovery');
INSERT INTO `irunaitem` VALUES('Chicken Orange Stew    ','Recovery');
INSERT INTO `irunaitem` VALUES('Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Classy Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Coconut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Coconut Water    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cola    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cooked Frog Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cooked Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cookie    ','Recovery');
INSERT INTO `irunaitem` VALUES('Crab Butter    ','Recovery');
INSERT INTO `irunaitem` VALUES('Crab Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Crab miso    ','Recovery');
INSERT INTO `irunaitem` VALUES('Crab Scissors    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cracked Mage Ore    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cream    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cream Puff    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cruel Evil Eye    ','Recovery');
INSERT INTO `irunaitem` VALUES('Cursed Evil Eye    ','Recovery');
INSERT INTO `irunaitem` VALUES('Daifuku    ','Recovery');
INSERT INTO `irunaitem` VALUES('Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Deep-fried Bean Curd    ','Recovery');
INSERT INTO `irunaitem` VALUES('Demi Hamburg Steak    ','Recovery');
INSERT INTO `irunaitem` VALUES('Diel Medicine    ','Recovery');
INSERT INTO `irunaitem` VALUES('dizziness dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Dragon Liquor    ','Recovery');
INSERT INTO `irunaitem` VALUES('Dragon Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Dragon Stone    ','Recovery');
INSERT INTO `irunaitem` VALUES('Dried Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Dried Seaweed    ','Recovery');
INSERT INTO `irunaitem` VALUES('Edamame    ','Recovery');
INSERT INTO `irunaitem` VALUES('Egg    ','Recovery');
INSERT INTO `irunaitem` VALUES('Eggplant    ','Recovery');
INSERT INTO `irunaitem` VALUES('Ehomaki    ','Recovery');
INSERT INTO `irunaitem` VALUES('Collecting Ehomaki Ingredients','');
INSERT INTO `irunaitem` VALUES('Elastic Bandage (Black)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Elastic Bandage (White)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Energy Drink    ','Recovery');
INSERT INTO `irunaitem` VALUES('Expert Potion    ','Recovery');
INSERT INTO `irunaitem` VALUES('Failed Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fancy Pet Food    ','Recovery');
INSERT INTO `irunaitem` VALUES('fear dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Firecracker    ','Recovery');
INSERT INTO `irunaitem` VALUES('Firely Spicy Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fish Cheek    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fish Head    ','Recovery');
INSERT INTO `irunaitem` VALUES('Forisco Grass    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fortune Shrine Water    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fortune-telling Candy    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fresh Fish    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fresh Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fresh Red Fish Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fresh White Fish Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Frog Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Frozen Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fruit Compote    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fruit of the mushroom    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fruit Punch    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fruit Revita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Fukumame    ','Recovery');
INSERT INTO `irunaitem` VALUES('Gladiator Revita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Goddess Tear    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grace Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grandy Bell Pepper    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grandy Coca    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grandy Corn    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grandy Potato    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grandy Tomato    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grape    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grape Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Griffin Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grilled fish    ','Recovery');
INSERT INTO `irunaitem` VALUES('Grilled White Meat Fish    ','Recovery');
INSERT INTO `irunaitem` VALUES('Ground Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Guild Remagic    ','Recovery');
INSERT INTO `irunaitem` VALUES('Guild Revita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Halloween Coin    ','Recovery');
INSERT INTO `irunaitem` VALUES('Hamburg Steak    ','Recovery');
INSERT INTO `irunaitem` VALUES('Handmade Choco    ','Recovery');
INSERT INTO `irunaitem` VALUES('Hard Egg    ','Recovery');
INSERT INTO `irunaitem` VALUES('Health Conversion    ','Recovery');
INSERT INTO `irunaitem` VALUES('high KO dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('high poison dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('High-class Potion    ','Recovery');
INSERT INTO `irunaitem` VALUES('Hinomaru Bento    ','Recovery');
INSERT INTO `irunaitem` VALUES('Hot Revita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Inari Sushi    ','Recovery');
INSERT INTO `irunaitem` VALUES('Irunayaki    ','Recovery');
INSERT INTO `irunaitem` VALUES('Jelly Steak    ','Recovery');
INSERT INTO `irunaitem` VALUES('Keema Curry    ','Recovery');
INSERT INTO `irunaitem` VALUES('Kijimu Leaf    ','Recovery');
INSERT INTO `irunaitem` VALUES('Kijimu Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Kitsune Udon    ','Recovery');
INSERT INTO `irunaitem` VALUES('KO Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Koya-dofu    ','Recovery');
INSERT INTO `irunaitem` VALUES('Large Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Leaf of Life    ','Recovery');
INSERT INTO `irunaitem` VALUES('Leather Canteen    ','Recovery');
INSERT INTO `irunaitem` VALUES('Leeds special chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Leek    ','Recovery');
INSERT INTO `irunaitem` VALUES('Lemon    ','Recovery');
INSERT INTO `irunaitem` VALUES('Lemon Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Life Fragment    ','Recovery');
INSERT INTO `irunaitem` VALUES('Life Oil    ','Recovery');
INSERT INTO `irunaitem` VALUES('Life Shard    ','Recovery');
INSERT INTO `irunaitem` VALUES('Life Soma    ','Recovery');
INSERT INTO `irunaitem` VALUES('Light Crystal    ','Recovery');
INSERT INTO `irunaitem` VALUES('Light Green Eggs    ','Recovery');
INSERT INTO `irunaitem` VALUES('Little Bean Pot    ','Recovery');
INSERT INTO `irunaitem` VALUES('Living Water    ','Recovery');
INSERT INTO `irunaitem` VALUES('Love Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Lucky Bean    ','Recovery');
INSERT INTO `irunaitem` VALUES('Lychee    ','Recovery');
INSERT INTO `irunaitem` VALUES('Magic Jar (Cold)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Magic Jar (Mud)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Magic Jar (Pure)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Magic Jar (Warm)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Magic Soma    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mango Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Maple Tea    ','Recovery');
INSERT INTO `irunaitem` VALUES('Marshmallow    ','Recovery');
INSERT INTO `irunaitem` VALUES('Medical Herb    ','Recovery');
INSERT INTO `irunaitem` VALUES('Medicinal Morel    ','Recovery');
INSERT INTO `irunaitem` VALUES('Medirita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Melon    ','Recovery');
INSERT INTO `irunaitem` VALUES('Melon Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Milk    ','Recovery');
INSERT INTO `irunaitem` VALUES('Miracle Tea    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mirin    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mitarashi Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mizu-Yokan    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mushroom Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mysterious Herb    ','Recovery');
INSERT INTO `irunaitem` VALUES('Nissa Manju    ','Recovery');
INSERT INTO `irunaitem` VALUES('Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Nutty Creme    ','Recovery');
INSERT INTO `irunaitem` VALUES('Obligation Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Ochazuke    ','Recovery');
INSERT INTO `irunaitem` VALUES('Okonomiyaki    ','Recovery');
INSERT INTO `irunaitem` VALUES('Onigiri    ','Recovery');
INSERT INTO `irunaitem` VALUES('Orange    ','Recovery');
INSERT INTO `irunaitem` VALUES('Orange Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Osechi    ','Recovery');
INSERT INTO `irunaitem` VALUES('Paralyze Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Peppercorn    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pet Food    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pickled Plum    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pineapple    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pineapple Cake    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pineapple Jelly    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pineapple Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pizza    ','Recovery');
INSERT INTO `irunaitem` VALUES('Poison Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Poison Mushroom    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pork    ','Recovery');
INSERT INTO `irunaitem` VALUES('Potato    ','Recovery');
INSERT INTO `irunaitem` VALUES('Powder Snow    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pumpkin    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pumpkin Candy    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pumpkin Juice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Pure Water    ','Recovery');
INSERT INTO `irunaitem` VALUES('Raid Remagic    ','Recovery');
INSERT INTO `irunaitem` VALUES('Raid Revita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Raisins    ','Recovery');
INSERT INTO `irunaitem` VALUES('Raw Egg of Life    ','Recovery');
INSERT INTO `irunaitem` VALUES('Red Cacao    ','Recovery');
INSERT INTO `irunaitem` VALUES('Red Meat Fish Zuke    ','Recovery');
INSERT INTO `irunaitem` VALUES('Regera (L)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Regera (M)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Regera (S)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Regera (XS)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Remagic (L)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Remagic (M)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Mana Wave 2','');
INSERT INTO `irunaitem` VALUES('Remagic (S)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Remagic (XL)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Remagic (XXL)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Revita (L)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Berserk 1','');
INSERT INTO `irunaitem` VALUES('Revita (M)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Revita (S)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Evil Santa','');
INSERT INTO `irunaitem` VALUES('Revita (S)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Goddess Statue at the Mine','');
INSERT INTO `irunaitem` VALUES('Revita (XL)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Revita (XXL)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Revita Ale    ','Recovery');
INSERT INTO `irunaitem` VALUES('Rice    ','Recovery');
INSERT INTO `irunaitem` VALUES('Rice and Curry    ','Recovery');
INSERT INTO `irunaitem` VALUES('Ripe Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Rita''s Test Medicine    ','Recovery');
INSERT INTO `irunaitem` VALUES('Roast bird    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sage Stone    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sake Gourd    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sake Steamed Clams    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sakuramochi    ','Recovery');
INSERT INTO `irunaitem` VALUES('Salt    ','Recovery');
INSERT INTO `irunaitem` VALUES('Salted Tongue    ','Recovery');
INSERT INTO `irunaitem` VALUES('Salty Leaf    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sashimi    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sauroin Steak    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sauteed Eggplant    ','Recovery');
INSERT INTO `irunaitem` VALUES('Scallops    ','Recovery');
INSERT INTO `irunaitem` VALUES('Scorpion Ale    ','Recovery');
INSERT INTO `irunaitem` VALUES('Scrambled Eggs    ','Recovery');
INSERT INTO `irunaitem` VALUES('Secret Source    ','Recovery');
INSERT INTO `irunaitem` VALUES('Shark Fin    ','Recovery');
INSERT INTO `irunaitem` VALUES('Slice of Cactus    ','Recovery');
INSERT INTO `irunaitem` VALUES('Snake Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Soft Cacao    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sorghum    ','Recovery');
INSERT INTO `irunaitem` VALUES('Soup Stock    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sour Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Soy Sauce    ','Recovery');
INSERT INTO `irunaitem` VALUES('Soybean Paste    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sp. Revita Ale    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sparkling Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Special Binal    ','Recovery');
INSERT INTO `irunaitem` VALUES('Special Regera    ','Recovery');
INSERT INTO `irunaitem` VALUES('Special Revita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Spicy Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Spicy Syrup    ','Recovery');
INSERT INTO `irunaitem` VALUES('Spinnen Energy Drink    ','Recovery');
INSERT INTO `irunaitem` VALUES('Spirita    ','Recovery');
INSERT INTO `irunaitem` VALUES('Stoic Seed    ','Recovery');
INSERT INTO `irunaitem` VALUES('Strange Fungus    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sugar    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sweet Chocolate    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sweet Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sweet Syrup    ','Recovery');
INSERT INTO `irunaitem` VALUES('Sweet-Sour Fruit    ','Recovery');
INSERT INTO `irunaitem` VALUES('Taiyaki    ','Recovery');
INSERT INTO `irunaitem` VALUES('Takoyaki    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tanuki''s Bottle    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tartar Sauce    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tasty Candy    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tasty Fish    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tasty Mushroom    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tasty Nut    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tasty Water    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tawa Chicken    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tenderloin Steak    ','Recovery');
INSERT INTO `irunaitem` VALUES('Thick Remagic (L)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Thick Remagic (M)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Thick Remagic (S)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Thick Revita (L)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Thick Revita (M)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Thick Revita (S)    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tomato    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tough Meat    ','Recovery');
INSERT INTO `irunaitem` VALUES('Treat Cookie    ','Recovery');
INSERT INTO `irunaitem` VALUES('Trick cookies    ','Recovery');
INSERT INTO `irunaitem` VALUES('Tricolor Dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Ultimate Carrot    ','Recovery');
INSERT INTO `irunaitem` VALUES('Umechazuke    ','Recovery');
INSERT INTO `irunaitem` VALUES('Unaju    ','Recovery');
INSERT INTO `irunaitem` VALUES('Unhulled Rice of Dawn    ','Recovery');
INSERT INTO `irunaitem` VALUES('Vinegar    ','Recovery');
INSERT INTO `irunaitem` VALUES('Watermelon    ','Recovery');
INSERT INTO `irunaitem` VALUES('weakness dango    ','Recovery');
INSERT INTO `irunaitem` VALUES('Wheat Beer    ','Recovery');
INSERT INTO `irunaitem` VALUES('White Bandage    ','Recovery');
INSERT INTO `irunaitem` VALUES('Whole Roast    ','Recovery');
INSERT INTO `irunaitem` VALUES('Witchcraft Cacao Beans    ','Recovery');
INSERT INTO `irunaitem` VALUES('Wooden Fish    ','Recovery');
INSERT INTO `irunaitem` VALUES('Xmas Bell    ','Recovery');
INSERT INTO `irunaitem` VALUES('Yakisoba    ','Recovery');
INSERT INTO `irunaitem` VALUES('Yogurt    ','Recovery');
INSERT INTO `irunaitem` VALUES('Yu Dofu    ','Recovery');
INSERT INTO `irunaitem` VALUES('Absolute Freeze Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Absolute Icicle Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Adistactos    ','Bows');
INSERT INTO `irunaitem` VALUES('Alnilam    ','Bows');
INSERT INTO `irunaitem` VALUES('Alnilam II    ','Bows');
INSERT INTO `irunaitem` VALUES('Alnilam III    ','Bows');
INSERT INTO `irunaitem` VALUES('Alnilam IV    ','Bows');
INSERT INTO `irunaitem` VALUES('Amaterasu    ','Bows');
INSERT INTO `irunaitem` VALUES('Amaterasu Masusume    ','Bows');
INSERT INTO `irunaitem` VALUES('Amaterasu Okami    ','Bows');
INSERT INTO `irunaitem` VALUES('Amaterasu Omikami    ','Bows');
INSERT INTO `irunaitem` VALUES('Amaterasu Sumeokami    ','Bows');
INSERT INTO `irunaitem` VALUES('Ameno Uzume    ','Bows');
INSERT INTO `irunaitem` VALUES('Angel Feather    ','Bows');
INSERT INTO `irunaitem` VALUES('Arcus Lilio    ','Bows');
INSERT INTO `irunaitem` VALUES('Arcus Lilio (Strengthened 1)    ','Bows');
INSERT INTO `irunaitem` VALUES('Arcus Lilio (Strengthened 2)    ','Bows');
INSERT INTO `irunaitem` VALUES('Assassin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Assassin Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES('Auroras Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Auroras Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Azure Ama    ','Bows');
INSERT INTO `irunaitem` VALUES('Azure Ama II    ','Bows');
INSERT INTO `irunaitem` VALUES('Bandit Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Beginner Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Beginner''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Bercrete    ','Bows');
INSERT INTO `irunaitem` VALUES('Bercrete II    ','Bows');
INSERT INTO `irunaitem` VALUES('Bercrete III    ','Bows');
INSERT INTO `irunaitem` VALUES('Blitz    ','Bows');
INSERT INTO `irunaitem` VALUES('Blitz+    ','Bows');
INSERT INTO `irunaitem` VALUES('Blue Sky    ','Bows');
INSERT INTO `irunaitem` VALUES('Bow of Kaiser    ','Bows');
INSERT INTO `irunaitem` VALUES('Bow of talent    ','Bows');
INSERT INTO `irunaitem` VALUES('Bow of talent II    ','Bows');
INSERT INTO `irunaitem` VALUES('Cabo Shooter    ','Bows');
INSERT INTO `irunaitem` VALUES('Canary Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Captain Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Captain Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES('Catalpa Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Celtis Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Celtis Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Celtis Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES('Centipede    ','Bows');
INSERT INTO `irunaitem` VALUES('Centipede II    ','Bows');
INSERT INTO `irunaitem` VALUES('Centipede III    ','Bows');
INSERT INTO `irunaitem` VALUES('Ceramic Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Ceramic Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Colonel Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Composite Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Compound Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Crimson Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Critical Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Diabolos    ','Bows');
INSERT INTO `irunaitem` VALUES('Diabolos II    ','Bows');
INSERT INTO `irunaitem` VALUES('Diabolos III    ','Bows');
INSERT INTO `irunaitem` VALUES('dimension    ','Bows');
INSERT INTO `irunaitem` VALUES('Dragon Paler    ','Bows');
INSERT INTO `irunaitem` VALUES('Dragon Techne    ','Bows');
INSERT INTO `irunaitem` VALUES('Earthshaker Briareus    ','Bows');
INSERT INTO `irunaitem` VALUES('Failnaught    ','Bows');
INSERT INTO `irunaitem` VALUES('Failnaught II    ','Bows');
INSERT INTO `irunaitem` VALUES('Failnaught III    ','Bows');
INSERT INTO `irunaitem` VALUES('Falconet    ','Bows');
INSERT INTO `irunaitem` VALUES('Falconet II    ','Bows');
INSERT INTO `irunaitem` VALUES('Falconet III    ','Bows');
INSERT INTO `irunaitem` VALUES('Fallen God''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Flame Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Fleurselman    ','Bows');
INSERT INTO `irunaitem` VALUES('Flugel    ','Bows');
INSERT INTO `irunaitem` VALUES('Freesia Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Freesia Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Gandiva    ','Bows');
INSERT INTO `irunaitem` VALUES('Gandiva II    ','Bows');
INSERT INTO `irunaitem` VALUES('Gandiva III    ','Bows');
INSERT INTO `irunaitem` VALUES('Gandiva IV    ','Bows');
INSERT INTO `irunaitem` VALUES('Gerifalte    ','Bows');
INSERT INTO `irunaitem` VALUES('Gerifalte II    ','Bows');
INSERT INTO `irunaitem` VALUES('Glacier Ark    ','Bows');
INSERT INTO `irunaitem` VALUES('Glacies    ','Bows');
INSERT INTO `irunaitem` VALUES('Glacies II    ','Bows');
INSERT INTO `irunaitem` VALUES('Golden Kite Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Grasegone    ','Bows');
INSERT INTO `irunaitem` VALUES('Hecaton Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Hecaton Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES('Hellfire Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Hiereus    ','Bows');
INSERT INTO `irunaitem` VALUES('Hiereus II    ','Bows');
INSERT INTO `irunaitem` VALUES('Hon-Shigeto Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Hunter''s Preparation Short Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Hunter''s Swordbow    ','Bows');
INSERT INTO `irunaitem` VALUES('Icicle Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Icicle Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Icicle Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES('Illusion Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Illusion Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Illusion Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES('Inari Hamayumi    ','Bows');
INSERT INTO `irunaitem` VALUES('Inari Hamayumi II    ','Bows');
INSERT INTO `irunaitem` VALUES('Indigo Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Indigo Breaker Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Indigo P. Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Inferno Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Irogeos Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Le Feu    ','Bows');
INSERT INTO `irunaitem` VALUES('Le Feu+    ','Bows');
INSERT INTO `irunaitem` VALUES('Le Feu+ II    ','Bows');
INSERT INTO `irunaitem` VALUES('Leek (Bow)    ','Bows');
INSERT INTO `irunaitem` VALUES('Leek II (Bow)    ','Bows');
INSERT INTO `irunaitem` VALUES('Long bow of Tert    ','Bows');
INSERT INTO `irunaitem` VALUES('Lueur Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Lueur Bow (Strengthened 1)    ','Bows');
INSERT INTO `irunaitem` VALUES('Malicia Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Mermaid Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Mermaid Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Migratale    ','Bows');
INSERT INTO `irunaitem` VALUES('Migratale II    ','Bows');
INSERT INTO `irunaitem` VALUES('Migratale III    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirage Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow FAG    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow FLF    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow FMA    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow FST    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow GAG    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow GLF    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow GMA    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow GST    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow IAG    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow ILF    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow IMA    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow IST    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow MAG    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow MC    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow MLF    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow MP    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow MR    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow MS    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow MST    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow PMA    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SAG    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SC    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SLF    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SMA    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SP    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SR    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SS    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow SST    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow TAG    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow TLF    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow TMA    ','Bows');
INSERT INTO `irunaitem` VALUES('Mirror Bow TST    ','Bows');
INSERT INTO `irunaitem` VALUES('Moonlight    ','Bows');
INSERT INTO `irunaitem` VALUES('Ocean Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Odium    ','Bows');
INSERT INTO `irunaitem` VALUES('Odium II    ','Bows');
INSERT INTO `irunaitem` VALUES('Odium III    ','Bows');
INSERT INTO `irunaitem` VALUES('Odium IV    ','Bows');
INSERT INTO `irunaitem` VALUES('parize bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Parring Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Pharmacist bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Pierret Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Plandra Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Plywood Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Present Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Private Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Protractor    ','Bows');
INSERT INTO `irunaitem` VALUES('Pumpkin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Pumpkin Shooter    ','Bows');
INSERT INTO `irunaitem` VALUES('Purgatory bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Quakeshaker Briareus    ','Bows');
INSERT INTO `irunaitem` VALUES('Quick Fire    ','Bows');
INSERT INTO `irunaitem` VALUES('Radiance Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Raijin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Raijodo    ','Bows');
INSERT INTO `irunaitem` VALUES('Rapid Fire    ','Bows');
INSERT INTO `irunaitem` VALUES('Recurve Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Reverse Shigeto Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Rising Ray    ','Bows');
INSERT INTO `irunaitem` VALUES('River Stone Moss Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter G1    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter G2    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter G3    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter G4    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro shooter L2    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter L3    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter L4    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter L5    ','Bows');
INSERT INTO `irunaitem` VALUES('Sauro Shooter L6    ','Bows');
INSERT INTO `irunaitem` VALUES('Savin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Seele Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Seele Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES('Seele Bow+ II    ','Bows');
INSERT INTO `irunaitem` VALUES('Seele Despell    ','Bows');
INSERT INTO `irunaitem` VALUES('Seelefuhr    ','Bows');
INSERT INTO `irunaitem` VALUES('Semeion    ','Bows');
INSERT INTO `irunaitem` VALUES('Semeion II    ','Bows');
INSERT INTO `irunaitem` VALUES('Semeion III    ','Bows');
INSERT INTO `irunaitem` VALUES('Semeion IV    ','Bows');
INSERT INTO `irunaitem` VALUES('Sepscorne    ','Bows');
INSERT INTO `irunaitem` VALUES('Serata Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Shigeto Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Sich Vort    ','Bows');
INSERT INTO `irunaitem` VALUES('Sich Vort II    ','Bows');
INSERT INTO `irunaitem` VALUES('Simoon    ','Bows');
INSERT INTO `irunaitem` VALUES('Slingshoot    ','Bows');
INSERT INTO `irunaitem` VALUES('Slingshot    ','Bows');
INSERT INTO `irunaitem` VALUES('Snatcher Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Sorciere Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Sorciere Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Stardust Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Starter Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Steel Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Storm Bow Sturm    ','Bows');
INSERT INTO `irunaitem` VALUES('Storm Bow Sturm II    ','Bows');
INSERT INTO `irunaitem` VALUES('Strike Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Strike Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Surge    ','Bows');
INSERT INTO `irunaitem` VALUES('Symbios Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Symbios Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES('Symbios Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES('Tail Arco    ','Bows');
INSERT INTO `irunaitem` VALUES('Tambourine    ','Bows');
INSERT INTO `irunaitem` VALUES('Termination Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Termination Bow +    ','Bows');
INSERT INTO `irunaitem` VALUES('Tiel''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Titan''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Total Remodeled Sling    ','Bows');
INSERT INTO `irunaitem` VALUES('Toy Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('vampire bow','Bows');
INSERT INTO `irunaitem` VALUES('Varota','Bows');
INSERT INTO `irunaitem` VALUES('Violaceum','Bows');
INSERT INTO `irunaitem` VALUES('Violafar','Bows');
INSERT INTO `irunaitem` VALUES('Violakarn    ','Bows');
INSERT INTO `irunaitem` VALUES('Violakrile    ','Bows');
INSERT INTO `irunaitem` VALUES('White Savior    ','Bows');
INSERT INTO `irunaitem` VALUES('Wing Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Wing Bow Sturm    ','Bows');
INSERT INTO `irunaitem` VALUES('Wooden Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('World Tree Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Wreath Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Yggdrasil Bow    ','Bows');
INSERT INTO `irunaitem` VALUES('Yumi    ','Bows');
COMMIT;
