
CREATE TABLE IF NOT EXISTS irunaitem
             (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'Absolute Freeze Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Absolute Icicle Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Adistactos    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Alnilam    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Alnilam II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Alnilam III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Alnilam IV    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Amaterasu    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Amaterasu Masusume    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Amaterasu Okami    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Amaterasu Omikami    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Amaterasu Sumeokami    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Ameno Uzume    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Angel Feather    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Arcus Lilio    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Arcus Lilio (Strengthened 1)    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Arcus Lilio (Strengthened 2)    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Assassin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Assassin Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Azure Ama    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Azure Ama II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Bandit Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Bercrete    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Bercrete II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Bercrete III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Blitz    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Blitz+    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Sky    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Bow of Kaiser    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Bow of talent    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Bow of talent II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Cabo Shooter    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Canary Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Captain Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Captain Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Catalpa Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Celtis Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Celtis Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Celtis Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Centipede    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Centipede II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Centipede III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Ceramic Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Ceramic Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Colonel Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Composite Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Compound Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Crimson Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Critical Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Diabolos    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Diabolos II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Diabolos III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'dimension    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Paler    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Techne    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Earthshaker Briareus    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Failnaught    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Failnaught II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Failnaught III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Falconet    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Falconet II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Falconet III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Fleurselman    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Flugel    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Gandiva    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Gandiva II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Gandiva III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Gandiva IV    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Gerifalte    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Gerifalte II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Glacier Ark    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Glacies    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Glacies II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Golden Kite Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Grasegone    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hecaton Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hecaton Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hellfire Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hiereus    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hiereus II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hon-Shigeto Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hunter''s Preparation Short Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Hunter''s Swordbow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Icicle Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Icicle Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Icicle Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Illusion Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Illusion Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Illusion Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Inari Hamayumi    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Inari Hamayumi II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Indigo Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Indigo Breaker Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Indigo P. Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Inferno Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Irogeos Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Le Feu    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Le Feu+    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Le Feu+ II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Leek (Bow)    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Leek II (Bow)    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Long bow of Tert    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Lueur Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Lueur Bow (Strengthened 1)    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Malicia Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mermaid Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mermaid Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Migratale    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Migratale II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Migratale III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirage Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow FAG    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow FLF    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow FMA    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow FST    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow GAG    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow GLF    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow GMA    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow GST    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow IAG    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow ILF    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow IMA    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow IST    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow MAG    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow MC    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow MLF    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow MP    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow MR    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow MS    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow MST    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow PMA    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SAG    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SC    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SLF    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SMA    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SP    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SR    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SS    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow SST    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow TAG    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow TLF    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow TMA    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Bow TST    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Moonlight    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Ocean Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Odium    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Odium II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Odium III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Odium IV    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'parize bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Parring Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Pharmacist bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Pierret Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Plandra Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Plywood Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Present Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Private Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Protractor    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Shooter    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Purgatory bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Quakeshaker Briareus    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Quick Fire    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Radiance Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Raijin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Raijodo    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Rapid Fire    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Recurve Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Reverse Shigeto Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Rising Ray    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'River Stone Moss Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter G1    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter G2    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter G3    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter G4    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro shooter L2    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter L3    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter L4    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter L5    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Shooter L6    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Savin Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Seele Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Seele Bow+    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Seele Bow+ II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Seele Despell    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Seelefuhr    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Semeion    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Semeion II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Semeion III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Semeion IV    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sepscorne    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Serata Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Shigeto Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sich Vort    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sich Vort II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Simoon    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Slingshoot    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Slingshot    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Snatcher Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sorciere Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Sorciere Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Stardust Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Starter Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Steel Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Storm Bow Sturm    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Storm Bow Sturm II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Strike Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Strike Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Surge    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Symbios Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Symbios Bow II    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Symbios Bow III    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Tail Arco    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Tambourine    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Termination Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Termination Bow +    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Tiel''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Titan''s Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Total Remodeled Sling    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Toy Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'vampire bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Varota    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Violaceum    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Violafar    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Violakarn    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Violakrile    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'White Savior    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Wing Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Wing Bow Sturm    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'World Tree Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Wreath Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Yggdrasil Bow    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Yumi    ','Bows');
INSERT INTO `irunaitem` VALUES(NULL,'Alacran    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Alacran II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Alacran III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Alacran IV    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Amber Sail    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Amber Sail II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Amber Sail III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Amber Sail IV    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Amber Sail V    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Asuranirrti    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Averse    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Averse II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Averse III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Azure Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Barba Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Barba Knuckle II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Barba Knuckle III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Battle Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'beast fang    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner''s Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Benesickle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Bilhawk    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Black Rose Chakram    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Blackboard Eraser    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Blast Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Blatt Arm    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Blatt Arm II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Blatt Arm III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Brigand Knife    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Carnyx    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Cat Paws    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Ceduro    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Ceduro II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Claw+    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Cremation    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Cremation II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Curse Nail    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Debby''s Talon    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon''s Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon''s Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon''s Claw III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Dragvelio    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Dragvelio II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Dragvelio III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Dragvelio IV    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Duel Nix    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Geiser    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Eclaire    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Eclaire II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Eclaire III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Eclaire IV    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Electric Beast Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Electric Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Electric Dragon Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Empedracle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Empedracle II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Empedracle III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Esmeralda    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Esmeralda II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Esmeralda III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Esmeralda IV    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Eve Pramia    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Evil Dog Glove    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Frost Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Gale Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Gargouille    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Gargouille II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Gargouille III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Girouette    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Girouette II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Glacier Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Glow Fists    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Grail    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Grail II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Granchio    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Guerra Nix    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Haze Fang    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Heart Snatcher    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'ice burn    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Crush    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Ignis Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Judgement    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Judgement II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Judgement III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Karga Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Knuckle Shield    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Knuckle Shield II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Knuckle Shield III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Kodachi    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Kodachi II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Kodachi III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Kodachi IV    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Lantern Row    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Letzel Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Light Duster    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Limni Knuckles    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Limni Knuckles II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Limni Knuckles III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Lobamineth    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Lobamineth II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Lobamineth III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Lyentia    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Lyentia II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Lyentia III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Cat    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mail Breaker    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Maniji    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Maniji II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Maniji III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mephisto Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Miasma the Cursed Blade    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Miasma the Cursed Blade II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Microphone Stand    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw FAG    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw FLF    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw FMA    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw FST    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw GAG    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw GLF    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw GMA    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw GST    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw IAG    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw ILF    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw IMA    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw IST    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw SC    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw SP    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw SR    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw SS    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw TAG    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw TLF    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw TMA    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Claw TST    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Nicht Alein    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Nicht Alein II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Obt Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Ocean Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Parasite Thorn    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Penet Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Pile Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'poisoned hands    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Pramia    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Pramia+    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Pramia++    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Predart knife    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Present Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Private Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Prox Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Punch    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpunch    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Purity Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Purity Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Purity Claw III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Rob Sickle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang G1    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang G2    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang G3    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang G4    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang L2    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang L3    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang L4    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Fang L5    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Savin Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sheep Shear    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sheep Shear II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sickle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sickle+    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sion Capell    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sion Capell II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sion Capell III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sirius Edge    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Sirius Edge II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Snead Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Snead Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Snead Claw III    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Soul Fist    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Soul Fist II    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Stake Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Tempest Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Testament    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Toy Gloves    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Traffic Cone    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Traveler Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Tree Claw    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Triangle    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Twin Goddess Aurora    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'Volare Knife    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'War nix    ','Claws');
INSERT INTO `irunaitem` VALUES(NULL,'zand snake    ','Claws');
COMMIT;
