
CREATE TABLE irunaitem
             (name text, category text);
INSERT INTO `irunaitem` VALUES('Alen''s Lexicon    ','Canes');
INSERT INTO `irunaitem` VALUES('Ambition    ','Canes');
INSERT INTO `irunaitem` VALUES('Amulet    ','Canes');
INSERT INTO `irunaitem` VALUES('Amulet+    ','Canes');
INSERT INTO `irunaitem` VALUES('Anti-Demon Mirror    ','Canes');
INSERT INTO `irunaitem` VALUES('Anti-Demon Mirror (Strengthened 1)    ','Canes');
INSERT INTO `irunaitem` VALUES('Aprile Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Aprilis Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Archbishop Scepter    ','Canes');
INSERT INTO `irunaitem` VALUES('Ark Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Armandel    ','Canes');
INSERT INTO `irunaitem` VALUES('Armandel Vol. 2    ','Canes');
INSERT INTO `irunaitem` VALUES('Armandel Vol. 3    ','Canes');
INSERT INTO `irunaitem` VALUES('Artemis Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Auroras Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Auroras Rod II    ','Canes');
INSERT INTO `irunaitem` VALUES('B・B・Q    ','Canes');
INSERT INTO `irunaitem` VALUES('Barotas    ','Canes');
INSERT INTO `irunaitem` VALUES('Barrier Dagger    ','Canes');
INSERT INTO `irunaitem` VALUES('Battle Mace    ','Canes');
INSERT INTO `irunaitem` VALUES('Beginner Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Beginner''s Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Bishop Scepter    ','Canes');
INSERT INTO `irunaitem` VALUES('Black Mage''s Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Black Wizard''s Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Blizzard Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Blue Claw Candle Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Blue Moon    ','Canes');
INSERT INTO `irunaitem` VALUES('Book of Thunder    ','Canes');
INSERT INTO `irunaitem` VALUES('Branch to Another World    ','Canes');
INSERT INTO `irunaitem` VALUES('Butterfly Fan    ','Canes');
INSERT INTO `irunaitem` VALUES('Butterfly Fan II    ','Canes');
INSERT INTO `irunaitem` VALUES('Butterfly Fan III    ','Canes');
INSERT INTO `irunaitem` VALUES('Butterfly Fan IV    ','Canes');
INSERT INTO `irunaitem` VALUES('Caduceus    ','Canes');
INSERT INTO `irunaitem` VALUES('Caduceus II    ','Canes');
INSERT INTO `irunaitem` VALUES('Caduceus III    ','Canes');
INSERT INTO `irunaitem` VALUES('Caduceus IV    ','Canes');
INSERT INTO `irunaitem` VALUES('Cane Candle Cane II    ','Canes');
INSERT INTO `irunaitem` VALUES('Cardinal Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Caterina Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Charm    ','Canes');
INSERT INTO `irunaitem` VALUES('Charm II    ','Canes');
INSERT INTO `irunaitem` VALUES('choir wand    ','Canes');
INSERT INTO `irunaitem` VALUES('condensation wand    ','Canes');
INSERT INTO `irunaitem` VALUES('Cotton Candy    ','Canes');
INSERT INTO `irunaitem` VALUES('Crescent Moon    ','Canes');
INSERT INTO `irunaitem` VALUES('Crescent Moon (Strengthened 1)    ','Canes');
INSERT INTO `irunaitem` VALUES('Hidden Powers','');
INSERT INTO `irunaitem` VALUES('Crescent Moon (Strengthened 2)    ','Canes');
INSERT INTO `irunaitem` VALUES('Crescent Moon (Strengthened 3)    ','Canes');
INSERT INTO `irunaitem` VALUES('Curse Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Dagger of Reflection    ','Canes');
INSERT INTO `irunaitem` VALUES('Dark Book    ','Canes');
INSERT INTO `irunaitem` VALUES('Dark Book Vol. 2    ','Canes');
INSERT INTO `irunaitem` VALUES('Dark Book Vol. 3    ','Canes');
INSERT INTO `irunaitem` VALUES('Dark Book Vol. 4    ','Canes');
INSERT INTO `irunaitem` VALUES('Dark Dragon Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Dark Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Death List    ','Canes');
INSERT INTO `irunaitem` VALUES('Deck Brush    ','Canes');
INSERT INTO `irunaitem` VALUES('Dielita    ','Canes');
INSERT INTO `irunaitem` VALUES('Dielita II    ','Canes');
INSERT INTO `irunaitem` VALUES('Dielita III    ','Canes');
INSERT INTO `irunaitem` VALUES('Dielita IV    ','Canes');
INSERT INTO `irunaitem` VALUES('Dinat Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Dragon Horn    ','Canes');
INSERT INTO `irunaitem` VALUES('Earth Dragon Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Earthquake Bell    ','Canes');
INSERT INTO `irunaitem` VALUES('Earthquake Bell II    ','Canes');
INSERT INTO `irunaitem` VALUES('Empress Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Enhance rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Esprimere    ','Canes');
INSERT INTO `irunaitem` VALUES('Esprimere II    ','Canes');
INSERT INTO `irunaitem` VALUES('Esprimere III    ','Canes');
INSERT INTO `irunaitem` VALUES('Fallen God''s Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Fast Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Feathered Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Fire Dragon Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Flame Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Flower Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Forbidden Book    ','Canes');
INSERT INTO `irunaitem` VALUES('Forbidden Book V    ','Canes');
INSERT INTO `irunaitem` VALUES('Forbidden Book Vol. 2    ','Canes');
INSERT INTO `irunaitem` VALUES('Forbidden Book Vol. 3    ','Canes');
INSERT INTO `irunaitem` VALUES('Forbidden Book Vol. 4    ','Canes');
INSERT INTO `irunaitem` VALUES('Forte Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Freesia Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Freesia Rod II    ','Canes');
INSERT INTO `irunaitem` VALUES('Fruru Revel    ','Canes');
INSERT INTO `irunaitem` VALUES('Fruru Revel II    ','Canes');
INSERT INTO `irunaitem` VALUES('Gato Negro    ','Canes');
INSERT INTO `irunaitem` VALUES('General Wand    ','Canes');
INSERT INTO `irunaitem` VALUES('General Wand II    ','Canes');
INSERT INTO `irunaitem` VALUES('General Wand III    ','Canes');
INSERT INTO `irunaitem` VALUES('Glacier Wand    ','Canes');
INSERT INTO `irunaitem` VALUES('Green Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Grimoire    ','Canes');
INSERT INTO `irunaitem` VALUES('hard stick cane    ','Canes');
INSERT INTO `irunaitem` VALUES('Harpoon    ','Canes');
INSERT INTO `irunaitem` VALUES('Hasakura Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Heal Branch    ','Canes');
INSERT INTO `irunaitem` VALUES('Heal Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Hermit Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Hermit Rod II    ','Canes');
INSERT INTO `irunaitem` VALUES('Hex Aura    ','Canes');
INSERT INTO `irunaitem` VALUES('holy angel wand    ','Canes');
INSERT INTO `irunaitem` VALUES('Hurricane Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Ice Book    ','Canes');
INSERT INTO `irunaitem` VALUES('Ice Book Vol. 2    ','Canes');
INSERT INTO `irunaitem` VALUES('Ice Book Vol. 3    ','Canes');
INSERT INTO `irunaitem` VALUES('Ice Book Vol. 4    ','Canes');
INSERT INTO `irunaitem` VALUES('Invariance    ','Canes');
INSERT INTO `irunaitem` VALUES('Joke Skull    ','Canes');
INSERT INTO `irunaitem` VALUES('Judgement Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Kerykeion    ','Canes');
INSERT INTO `irunaitem` VALUES('Kerykeion II    ','Canes');
INSERT INTO `irunaitem` VALUES('Kerykeion III    ','Canes');
INSERT INTO `irunaitem` VALUES('Laney Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Leek (Staff)    ','Canes');
INSERT INTO `irunaitem` VALUES('Leek II (Staff)    ','Canes');
INSERT INTO `irunaitem` VALUES('Lespolt Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Light Dragon Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Light Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Lotus leaf    ','Canes');
INSERT INTO `irunaitem` VALUES('Luna Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Mace    ','Canes');
INSERT INTO `irunaitem` VALUES('Machtrario    ','Canes');
INSERT INTO `irunaitem` VALUES('Machtrario II    ','Canes');
INSERT INTO `irunaitem` VALUES('Machtrario III    ','Canes');
INSERT INTO `irunaitem` VALUES('Mage Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Magia Knife    ','Canes');
INSERT INTO `irunaitem` VALUES('Magia Knife II    ','Canes');
INSERT INTO `irunaitem` VALUES('Magic Dagger    ','Canes');
INSERT INTO `irunaitem` VALUES('Megistus Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Microscope    ','Canes');
INSERT INTO `irunaitem` VALUES('mirage dagger    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod FAG    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod FLF    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod FMA    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod FST    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod GAG    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod GLF    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod GMA    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod GST    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod IAG    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod ILF    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod IMA    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod IST    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod MAG    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod MC    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod MLF    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod MP    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod MR    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod MS    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod MST    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod PMA    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod TAG    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod TLF    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod TMA    ','Canes');
INSERT INTO `irunaitem` VALUES('Mirror Rod TST    ','Canes');
INSERT INTO `irunaitem` VALUES('Mortal Dagger    ','Canes');
INSERT INTO `irunaitem` VALUES('Necro Wand    ','Canes');
INSERT INTO `irunaitem` VALUES('Neve Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Ocean Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Paraxenos    ','Canes');
INSERT INTO `irunaitem` VALUES('Petal Scream    ','Canes');
INSERT INTO `irunaitem` VALUES('Phoenix Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Phoenix Staff II    ','Canes');
INSERT INTO `irunaitem` VALUES('Phoenix Staff III    ','Canes');
INSERT INTO `irunaitem` VALUES('Present Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Priest Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Princely Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Private Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Pumpkin Book    ','Canes');
INSERT INTO `irunaitem` VALUES('Pumpkin Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Quake Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Queen Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Raziel Code    ','Canes');
INSERT INTO `irunaitem` VALUES('Raziel Code II    ','Canes');
INSERT INTO `irunaitem` VALUES('Raziel Code III    ','Canes');
INSERT INTO `irunaitem` VALUES('Raziel Code IV    ','Canes');
INSERT INTO `irunaitem` VALUES('Resolve Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Resty Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Resty Rod (Strengthened 1)    ','Canes');
INSERT INTO `irunaitem` VALUES('rich staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Ritual Book    ','Canes');
INSERT INTO `irunaitem` VALUES('Ritual Book Vol. 2    ','Canes');
INSERT INTO `irunaitem` VALUES('Ritual Book Vol. 3    ','Canes');
INSERT INTO `irunaitem` VALUES('Royal Nectar    ','Canes');
INSERT INTO `irunaitem` VALUES('Sage Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Saint Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Saint Rod II    ','Canes');
INSERT INTO `irunaitem` VALUES('Saint''s Scripture    ','Canes');
INSERT INTO `irunaitem` VALUES('Sandtester    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick G1    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick G2    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick G3    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick G4    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick L2    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick L3    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick L4    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick L5    ','Canes');
INSERT INTO `irunaitem` VALUES('Sauro Stick L6    ','Canes');
INSERT INTO `irunaitem` VALUES('Savin Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('School Broom    ','Canes');
INSERT INTO `irunaitem` VALUES('Snowman''s Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Solve Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Solve Rod+    ','Canes');
INSERT INTO `irunaitem` VALUES('Solver Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Sonic Hand    ','Canes');
INSERT INTO `irunaitem` VALUES('Spell Book    ','Canes');
INSERT INTO `irunaitem` VALUES('Spell Book Vol. 2    ','Canes');
INSERT INTO `irunaitem` VALUES('Spell Book Vol. 3    ','Canes');
INSERT INTO `irunaitem` VALUES('Spell Book Vol.4    ','Canes');
INSERT INTO `irunaitem` VALUES('Spell Book Vol.5    ','Canes');
INSERT INTO `irunaitem` VALUES('Staff of Dawn    ','Canes');
INSERT INTO `irunaitem` VALUES('Starlight Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Starter Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Storm Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Stroz Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Stroz Rod II    ','Canes');
INSERT INTO `irunaitem` VALUES('Stroz Rod III    ','Canes');
INSERT INTO `irunaitem` VALUES('Sunny Crystal    ','Canes');
INSERT INTO `irunaitem` VALUES('Sword Amulet    ','Canes');
INSERT INTO `irunaitem` VALUES('Sword Amulet (Strengthened)    ','Canes');
INSERT INTO `irunaitem` VALUES('Sylph Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Talisman Sword    ','Canes');
INSERT INTO `irunaitem` VALUES('Tellas Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Tellas Rod II    ','Canes');
INSERT INTO `irunaitem` VALUES('Throat Knife    ','Canes');
INSERT INTO `irunaitem` VALUES('Thunder Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Tokoyo no Mihitaki    ','Canes');
INSERT INTO `irunaitem` VALUES('Traveler Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Triaina    ','Canes');
INSERT INTO `irunaitem` VALUES('Trident    ','Canes');
INSERT INTO `irunaitem` VALUES('Trishula    ','Canes');
INSERT INTO `irunaitem` VALUES('Trishula II    ','Canes');
INSERT INTO `irunaitem` VALUES('True Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Tsarita Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Tuning Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Uber Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Universe    ','Canes');
INSERT INTO `irunaitem` VALUES('Universe II    ','Canes');
INSERT INTO `irunaitem` VALUES('Universe III    ','Canes');
INSERT INTO `irunaitem` VALUES('Utsushiyo no Imibi    ','Canes');
INSERT INTO `irunaitem` VALUES('Vajra    ','Canes');
INSERT INTO `irunaitem` VALUES('Vajra II    ','Canes');
INSERT INTO `irunaitem` VALUES('Valida Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('VDA Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Velum Mace    ','Canes');
INSERT INTO `irunaitem` VALUES('Venity Lily    ','Canes');
INSERT INTO `irunaitem` VALUES('Vouivre    ','Canes');
INSERT INTO `irunaitem` VALUES('Vouivre II    ','Canes');
INSERT INTO `irunaitem` VALUES('Water Dragon Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Wind Dragon Staff    ','Canes');
INSERT INTO `irunaitem` VALUES('Wing Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Witch Knife    ','Canes');
INSERT INTO `irunaitem` VALUES('Wizard Rod    ','Canes');
INSERT INTO `irunaitem` VALUES('Wooden Cane    ','Canes');
INSERT INTO `irunaitem` VALUES('Alacran    ','Claws');
INSERT INTO `irunaitem` VALUES('Alacran II    ','Claws');
INSERT INTO `irunaitem` VALUES('Alacran III    ','Claws');
INSERT INTO `irunaitem` VALUES('Alacran IV    ','Claws');
INSERT INTO `irunaitem` VALUES('Amber Sail    ','Claws');
INSERT INTO `irunaitem` VALUES('Amber Sail II    ','Claws');
INSERT INTO `irunaitem` VALUES('Amber Sail III    ','Claws');
INSERT INTO `irunaitem` VALUES('Amber Sail IV    ','Claws');
INSERT INTO `irunaitem` VALUES('Amber Sail V    ','Claws');
INSERT INTO `irunaitem` VALUES('Asuranirrti    ','Claws');
INSERT INTO `irunaitem` VALUES('Auroras Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Auroras Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES('Averse    ','Claws');
INSERT INTO `irunaitem` VALUES('Averse II    ','Claws');
INSERT INTO `irunaitem` VALUES('Averse III    ','Claws');
INSERT INTO `irunaitem` VALUES('Azure Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Barba Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES('Barba Knuckle II    ','Claws');
INSERT INTO `irunaitem` VALUES('Barba Knuckle III    ','Claws');
INSERT INTO `irunaitem` VALUES('Battle Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('beast fang    ','Claws');
INSERT INTO `irunaitem` VALUES('Beginner Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Beginner''s Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Benesickle    ','Claws');
INSERT INTO `irunaitem` VALUES('Bilhawk    ','Claws');
INSERT INTO `irunaitem` VALUES('Black Rose Chakram    ','Claws');
INSERT INTO `irunaitem` VALUES('Blackboard Eraser    ','Claws');
INSERT INTO `irunaitem` VALUES('Blast Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Blatt Arm    ','Claws');
INSERT INTO `irunaitem` VALUES('Blatt Arm II    ','Claws');
INSERT INTO `irunaitem` VALUES('Blatt Arm III    ','Claws');
INSERT INTO `irunaitem` VALUES('Brigand Knife    ','Claws');
INSERT INTO `irunaitem` VALUES('Carnyx    ','Claws');
INSERT INTO `irunaitem` VALUES('Cat Paws    ','Claws');
INSERT INTO `irunaitem` VALUES('Ceduro    ','Claws');
INSERT INTO `irunaitem` VALUES('Ceduro II    ','Claws');
INSERT INTO `irunaitem` VALUES('Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Claw+    ','Claws');
INSERT INTO `irunaitem` VALUES('Cremation    ','Claws');
INSERT INTO `irunaitem` VALUES('Cremation II    ','Claws');
INSERT INTO `irunaitem` VALUES('Curse Nail    ','Claws');
INSERT INTO `irunaitem` VALUES('Debby''s Talon    ','Claws');
INSERT INTO `irunaitem` VALUES('Dragon''s Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Dragon''s Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES('Dragon''s Claw III    ','Claws');
INSERT INTO `irunaitem` VALUES('Dragvelio    ','Claws');
INSERT INTO `irunaitem` VALUES('Dragvelio II    ','Claws');
INSERT INTO `irunaitem` VALUES('Dragvelio III    ','Claws');
INSERT INTO `irunaitem` VALUES('Dragvelio IV    ','Claws');
INSERT INTO `irunaitem` VALUES('Duel Nix    ','Claws');
INSERT INTO `irunaitem` VALUES('Earth Geiser    ','Claws');
INSERT INTO `irunaitem` VALUES('Eclaire    ','Claws');
INSERT INTO `irunaitem` VALUES('Eclaire II    ','Claws');
INSERT INTO `irunaitem` VALUES('Eclaire III    ','Claws');
INSERT INTO `irunaitem` VALUES('Eclaire IV    ','Claws');
INSERT INTO `irunaitem` VALUES('Electric Beast Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Electric Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Electric Dragon Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Empedracle    ','Claws');
INSERT INTO `irunaitem` VALUES('Empedracle II    ','Claws');
INSERT INTO `irunaitem` VALUES('Empedracle III    ','Claws');
INSERT INTO `irunaitem` VALUES('Esmeralda    ','Claws');
INSERT INTO `irunaitem` VALUES('Esmeralda II    ','Claws');
INSERT INTO `irunaitem` VALUES('Esmeralda III    ','Claws');
INSERT INTO `irunaitem` VALUES('Esmeralda IV    ','Claws');
INSERT INTO `irunaitem` VALUES('Eve Pramia    ','Claws');
INSERT INTO `irunaitem` VALUES('Evil Dog Glove    ','Claws');
INSERT INTO `irunaitem` VALUES('Fallen God''s Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Flame Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Flame Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES('Freesia Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Freesia Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES('Frost Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Gale Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Gargouille    ','Claws');
INSERT INTO `irunaitem` VALUES('Gargouille II    ','Claws');
INSERT INTO `irunaitem` VALUES('Gargouille III    ','Claws');
INSERT INTO `irunaitem` VALUES('Girouette    ','Claws');
INSERT INTO `irunaitem` VALUES('Girouette II    ','Claws');
INSERT INTO `irunaitem` VALUES('Glacier Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Glow Fists    ','Claws');
INSERT INTO `irunaitem` VALUES('Grail    ','Claws');
INSERT INTO `irunaitem` VALUES('Grail II    ','Claws');
INSERT INTO `irunaitem` VALUES('Granchio    ','Claws');
INSERT INTO `irunaitem` VALUES('Guerra Nix    ','Claws');
INSERT INTO `irunaitem` VALUES('Haze Fang    ','Claws');
INSERT INTO `irunaitem` VALUES('Heart Snatcher    ','Claws');
INSERT INTO `irunaitem` VALUES('ice burn    ','Claws');
INSERT INTO `irunaitem` VALUES('Ice Crush    ','Claws');
INSERT INTO `irunaitem` VALUES('Ignis Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Judgement    ','Claws');
INSERT INTO `irunaitem` VALUES('Judgement II    ','Claws');
INSERT INTO `irunaitem` VALUES('Judgement III    ','Claws');
INSERT INTO `irunaitem` VALUES('Karga Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES('Knuckle Shield    ','Claws');
INSERT INTO `irunaitem` VALUES('Knuckle Shield II    ','Claws');
INSERT INTO `irunaitem` VALUES('Knuckle Shield III    ','Claws');
INSERT INTO `irunaitem` VALUES('Kodachi    ','Claws');
INSERT INTO `irunaitem` VALUES('Kodachi II    ','Claws');
INSERT INTO `irunaitem` VALUES('Kodachi III    ','Claws');
INSERT INTO `irunaitem` VALUES('Kodachi IV    ','Claws');
INSERT INTO `irunaitem` VALUES('Lantern Row    ','Claws');
INSERT INTO `irunaitem` VALUES('Letzel Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Light Duster    ','Claws');
INSERT INTO `irunaitem` VALUES('Limni Knuckles    ','Claws');
INSERT INTO `irunaitem` VALUES('Limni Knuckles II    ','Claws');
INSERT INTO `irunaitem` VALUES('Limni Knuckles III    ','Claws');
INSERT INTO `irunaitem` VALUES('Lobamineth    ','Claws');
INSERT INTO `irunaitem` VALUES('Lobamineth II    ','Claws');
INSERT INTO `irunaitem` VALUES('Lobamineth III    ','Claws');
INSERT INTO `irunaitem` VALUES('Lyentia    ','Claws');
INSERT INTO `irunaitem` VALUES('Lyentia II    ','Claws');
INSERT INTO `irunaitem` VALUES('Lyentia III    ','Claws');
INSERT INTO `irunaitem` VALUES('Magic Cat    ','Claws');
INSERT INTO `irunaitem` VALUES('Mail Breaker    ','Claws');
INSERT INTO `irunaitem` VALUES('Maniji    ','Claws');
INSERT INTO `irunaitem` VALUES('Maniji II    ','Claws');
INSERT INTO `irunaitem` VALUES('Maniji III    ','Claws');
INSERT INTO `irunaitem` VALUES('Mephisto Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Miasma the Cursed Blade    ','Claws');
INSERT INTO `irunaitem` VALUES('Miasma the Cursed Blade II    ','Claws');
INSERT INTO `irunaitem` VALUES('Microphone Stand    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw FAG    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw FLF    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw FMA    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw FST    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw GAG    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw GLF    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw GMA    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw GST    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw IAG    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw ILF    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw IMA    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw IST    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw SC    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw SP    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw SR    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw SS    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw TAG    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw TLF    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw TMA    ','Claws');
INSERT INTO `irunaitem` VALUES('Mirror Claw TST    ','Claws');
INSERT INTO `irunaitem` VALUES('Nicht Alein    ','Claws');
INSERT INTO `irunaitem` VALUES('Nicht Alein II    ','Claws');
INSERT INTO `irunaitem` VALUES('Obt Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Ocean Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Parasite Thorn    ','Claws');
INSERT INTO `irunaitem` VALUES('Penet Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES('Pile Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES('poisoned hands    ','Claws');
INSERT INTO `irunaitem` VALUES('Pramia    ','Claws');
INSERT INTO `irunaitem` VALUES('Pramia+    ','Claws');
INSERT INTO `irunaitem` VALUES('Pramia++    ','Claws');
INSERT INTO `irunaitem` VALUES('Predart knife    ','Claws');
INSERT INTO `irunaitem` VALUES('Present Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Private Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Prox Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Pumpkin Punch    ','Claws');
INSERT INTO `irunaitem` VALUES('Pumpunch    ','Claws');
INSERT INTO `irunaitem` VALUES('Purity Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Purity Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES('Purity Claw III    ','Claws');
INSERT INTO `irunaitem` VALUES('Rob Sickle    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang G1    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang G2    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang G3    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang G4    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang L2    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang L3    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang L4    ','Claws');
INSERT INTO `irunaitem` VALUES('Sauro Fang L5    ','Claws');
INSERT INTO `irunaitem` VALUES('Savin Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Sheep Shear    ','Claws');
INSERT INTO `irunaitem` VALUES('Sheep Shear II    ','Claws');
INSERT INTO `irunaitem` VALUES('Sickle    ','Claws');
INSERT INTO `irunaitem` VALUES('Sickle+    ','Claws');
INSERT INTO `irunaitem` VALUES('Sion Capell    ','Claws');
INSERT INTO `irunaitem` VALUES('Sion Capell II    ','Claws');
INSERT INTO `irunaitem` VALUES('Sion Capell III    ','Claws');
INSERT INTO `irunaitem` VALUES('Sirius Edge    ','Claws');
INSERT INTO `irunaitem` VALUES('Sirius Edge II    ','Claws');
INSERT INTO `irunaitem` VALUES('Snead Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Snead Claw II    ','Claws');
INSERT INTO `irunaitem` VALUES('Snead Claw III    ','Claws');
INSERT INTO `irunaitem` VALUES('Soul Fist    ','Claws');
INSERT INTO `irunaitem` VALUES('Soul Fist II    ','Claws');
INSERT INTO `irunaitem` VALUES('Stake Knuckle    ','Claws');
INSERT INTO `irunaitem` VALUES('Tempest Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Testament    ','Claws');
INSERT INTO `irunaitem` VALUES('Toy Gloves    ','Claws');
INSERT INTO `irunaitem` VALUES('Traffic Cone    ','Claws');
INSERT INTO `irunaitem` VALUES('Traveler Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Tree Claw    ','Claws');
INSERT INTO `irunaitem` VALUES('Triangle    ','Claws');
INSERT INTO `irunaitem` VALUES('Twin Goddess Aurora    ','Claws');
INSERT INTO `irunaitem` VALUES('Volare Knife    ','Claws');
INSERT INTO `irunaitem` VALUES('War nix    ','Claws');
INSERT INTO `irunaitem` VALUES('zand snake    ','Claws');
INSERT INTO `irunaitem` VALUES('Angel Item    ','Chests');
INSERT INTO `irunaitem` VALUES('Bernard Candy Bag    ','Chests');
INSERT INTO `irunaitem` VALUES('Black Silver Feather    ','Chests');
INSERT INTO `irunaitem` VALUES('Blue Box    ','Chests');
INSERT INTO `irunaitem` VALUES('Candy bag    ','Chests');
INSERT INTO `irunaitem` VALUES('Dirty Magic Book    ','Chests');
INSERT INTO `irunaitem` VALUES('Fallen God''s Empty Vessel    ','Chests');
INSERT INTO `irunaitem` VALUES('Freesia Bead    ','Chests');
INSERT INTO `irunaitem` VALUES('G. Power    ','Chests');
INSERT INTO `irunaitem` VALUES('Gold Chest    ','Chests');
INSERT INTO `irunaitem` VALUES('Gold Orb    ','Chests');
INSERT INTO `irunaitem` VALUES('Jewel Box    ','Chests');
INSERT INTO `irunaitem` VALUES('Lucky Bag: Ore    ','Chests');
INSERT INTO `irunaitem` VALUES('Lucky Bag: Seed    ','Chests');
INSERT INTO `irunaitem` VALUES('Magic Lamp    ','Chests');
INSERT INTO `irunaitem` VALUES('Octocur Candy Bag    ','Chests');
INSERT INTO `irunaitem` VALUES('Old Treasure Box    ','Chests');
INSERT INTO `irunaitem` VALUES('Ore box    ','Chests');
INSERT INTO `irunaitem` VALUES('Pumpkin Dress Box    ','Chests');
INSERT INTO `irunaitem` VALUES('Raid Box A    ','Chests');
INSERT INTO `irunaitem` VALUES('Raid Box B    ','Chests');
INSERT INTO `irunaitem` VALUES('Raid Box C    ','Chests');
INSERT INTO `irunaitem` VALUES('Raid Box D    ','Chests');
INSERT INTO `irunaitem` VALUES('Raid Box E    ','Chests');
INSERT INTO `irunaitem` VALUES('Raid Orb A    ','Chests');
INSERT INTO `irunaitem` VALUES('Red Box    ','Chests');
INSERT INTO `irunaitem` VALUES('Sauro''s Chest    ','Chests');
INSERT INTO `irunaitem` VALUES('Sauro''s Chest 2    ','Chests');
INSERT INTO `irunaitem` VALUES('Sauro''s Chest 3    ','Chests');
INSERT INTO `irunaitem` VALUES('Sauro''s Chest 4    ','Chests');
INSERT INTO `irunaitem` VALUES('Sauro''s Chest V    ','Chests');
INSERT INTO `irunaitem` VALUES('Sauro''s Gold Chest    ','Chests');
INSERT INTO `irunaitem` VALUES('Snowflake Blessing    ','Chests');
INSERT INTO `irunaitem` VALUES('Sweet Bouquet    ','Chests');
INSERT INTO `irunaitem` VALUES('Treasure Box    ','Chests');
INSERT INTO `irunaitem` VALUES('White Silver Feather    ','Chests');
INSERT INTO `irunaitem` VALUES('Xmas Present    ','Chests');
INSERT INTO `irunaitem` VALUES('Disappeared Santa Sack','');
INSERT INTO `irunaitem` VALUES('Xmas Present 2    ','Chests');
COMMIT;
