
CREATE TABLE IF NOT EXISTS irunaitem
 (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'Albedo Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Ale Keg','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Anvil','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Arched Bridge','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Arched Bridge Ab.','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bean Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bernard Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Blanc Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Block','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bronze Candelabrum','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bronze Candlestick','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Brosch Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Chair','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Chako Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Colon Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Corn Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Eerie Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Field King Bust','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks A','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks B','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks C','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks D','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks E','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks H','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks I','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Flowerbed','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Flowerbed (L)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gemic Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Candelabrum','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Candlestick','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Colon Icon','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Cutlery','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Golden Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Carrot','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Napa Cabbage','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Radish','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Stump','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Tomato Planter','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grass Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Green Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Green Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Griffin Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Basalt)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Granite)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Jasper)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Obsidian)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Pyrite)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Halloween Tails Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Block','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Pillar','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Iris Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Rice Cooker','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Leek Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Maneki-Neko Altar','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Maneki-Neko Statue (S)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mani Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (A&T)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (D)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (G)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (M)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (T)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (V)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mini Cactus','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mini Haniwa','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mini Snowman','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Miwi Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Moeba Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mooth Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'New Year Deco.','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Nigredo Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Noah Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Octocur Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Okiri Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Oni Stone Lantern','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Pengino Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Piton Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Potted Plant','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Potted Tree','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Purple Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Rafflesia Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Red Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Red Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Rose Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Rowell Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Candelabrum','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Candlestick','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Cutlery','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Skull','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Slime Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Snow Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Snow Sculpture','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Snowman Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Stacked Bean Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Stacked Golden Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Stock Pot','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Table','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Tomato Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Tri-Tail Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wok','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Hand Pail','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Pail','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Poke','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Cake B','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Wreath','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'ドンペン人形','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'ビーチルナ人形','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'★ Altoale Sector','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Aqruf Town','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Caldera village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Elban','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Eldan','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Saterica','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Sofya','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dark Castle','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dark Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dark Santa','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Deeos village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Diel Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Divine Tower','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dorry','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Drafbourg','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Earth Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Eryldan Desert','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Fire Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Food Storage','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Fort Bailune','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Ganaji Strand','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Heaven Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Histaria','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Ioleu Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Justice Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kakeula City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kilf Plains','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kleven Corridor','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kleya City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kreldan','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kreya City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Leelids Field','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Lograth City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Lunite Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Lydia','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Maios','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Maldario','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Mawid Plains','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Maze of Enzeits','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Mercy Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Minaula City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Mioreita Castle','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Nidea coast','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Oltoga Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Orolhool','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Ouvels Chamber','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Peace Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Pilaneza City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Port Spargas','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Reoctove','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Rokoko City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Rokoko Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Roye Underground Church','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Rudolf','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Sateria City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Sauro Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Sofia Street','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Specia Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ special blacksmith','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Underground Bailune','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Upper Palace','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Varant Town','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ War Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Water Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Wibo City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Wind Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Windstone','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Wisdom Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Xaofks','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'Blank invitation','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'Isle Invitation','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'◆Aid','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◆Assault','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◆Mana Wave','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◆Mini Heal','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◆Provoke','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◆Sonic Boom','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◆Spell Boost','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◆Vampire Blow','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇10th Anniversary','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇A. Evasion +1%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Absolute Evasion +2%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Aello','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI&DEX+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI&DEX+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI&DEX+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI&DEX+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI&DEX+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇AGI+7','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Agira Jarma','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Agni','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Agoracanth','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Alchemist''s Soul','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Aldi','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Almas','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Altadora','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Amatis','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇ANGA','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Anubites','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Aoi Eisen','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Argyros','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Arick','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇ATK+10','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇ATK+15','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇ATK+20','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇ＡＴＫ＋２５','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Aungyo','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Aurumteus','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Avazel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Azimov','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Bancho Muscle','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Bancho Piton','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Barafu','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Beelzebub','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Beelzed','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Beelzedam','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Beelzenoid','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Beelzenom','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Beelzetor','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Belial','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Bernard','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Black Dark Warrior','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Blaiard','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Blaiard II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Blatt','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Blauzen','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Blitz','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Blue Ogre','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Blue Rain','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Bodyguard Cordal','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Bongea','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Boss Colon','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Boss Mimic','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Bossheit','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Botanian','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Botaniga','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Bridegroom Enfar','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Burnos','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Captain Beelzem','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Carinae','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Carpenter''s Soul','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cast I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cast II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cast III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Catafnia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Causal Storm','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cecilia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Celaeno','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Celawinos','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cerberus','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Chasing''s Soul','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cherose','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Civil','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Coagulum','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Colon Tree','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cooker''s Soul','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Cooperin','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Crescent','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Critical I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Critical II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Critical III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇CRT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇CRT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇CRT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇CRT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇CRT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇CRT+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇CRT+7','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Curonne','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Daemon','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dajarte','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dark Crystal','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dark Enhancer I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dark Enhancer II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dark Enhancer III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dark Santa','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dark Santa II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEF+1%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEF+2%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEF+3%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEF+4%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEF+5%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Degizman','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX&CRT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX&CRT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX&CRT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX&CRT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX&CRT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇DEX+7','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dooms','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dorry','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Douin','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Drag-o''-Lantern','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dragil','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dullahan','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dunkelis','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Dunkelis II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Earth Enhancer I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Earth Enhancer II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Earth Enhancer III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Easter','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ebon Knight','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Echidna','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Eisen','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Eisen II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Eldas','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Elec','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Empty Crysta','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Enfar','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Extract Crysta','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Eye Magi King','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇False Grecia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Felinike','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ferzen','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ferzen II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Festival Colon','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Fimbul','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Finstern','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Fiona','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Fiore Hinete','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Fire Enhancer I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Fire Enhancer II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Fire Enhancer III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Flame of mission','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Flammel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Flora','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Foxxus','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Fred','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Frederico','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Freedos','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Frigate','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Frosches','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇G. Sauro','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gadave','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ganei','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ganesha','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gankaku','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Garel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gashadororo','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gefryl','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gerust','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gewalt','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ghoulie','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Giant Rocker','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gilgobble','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ginami','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gloenra','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Grail','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Grapagos','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Grecia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Grecia II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Guevol','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Gusanoth','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Halios','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Hamewlin','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Harno','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Heaven Gate Corporal','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Hicolon','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Himmel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HIT+10','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HIT+20','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HIT+25','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HIT+30','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HIT+35','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HIT+40','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HP Regen+10','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HP Regen+12','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HP Regen+14','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HP Regen+16','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HP Regen+18','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇HP Regen+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Hydra','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ibrie','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ice of the life','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ideaus','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ifrit','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Igro','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Imseti','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ingrid','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Iniliba','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&CRT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&CRT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&CRT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&CRT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&CRT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&VIT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&VIT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&VIT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&VIT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT&VIT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇INT+7','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Interfike','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Irai','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Isurugi Statue','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Item DT','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Jabek','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Jahoel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kagan','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kaise Pilz','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kaiser','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kaiser II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kaphar','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kigende','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kimale','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇King Fugue','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Kinote','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Laster','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Leese','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Leviathan','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Light Enhancer I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Light Enhancer II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Light Enhancer III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Lipka','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Lord of Nezim','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Lorelei','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Lost Knight','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇M. Evasion +1%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Magic Evasion +2%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Magic Resistance I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Magic Resistance II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Magic+120','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Magic+70','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Magic+95','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇magical weapon','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Magonza','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mamionette','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mani','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Matadora','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Matar','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MATK+10','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MATK+20','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MATK+30','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇ＭＡＴＫ＋４０','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP + 20','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+100','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+11%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+14%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+17%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+20%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+200','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+300','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+400','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+500','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+600','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+700','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxHP+8%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+11%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+120','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+13%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+150','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+180','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+210','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+30','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+5%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+60','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+7%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+9%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MaxMP+90','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MDEF+1%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MDEF+2%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MDEF+3%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MDEF+4%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MDEF+5%','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Medetai','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Medical I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Medical II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Medical III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Medona','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Melee Resistance I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Melee Resistance II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Melee+10','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Melee+20','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Melee+30','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Melee+40','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Melee+50','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Meligia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Memecoleous','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Metal Saulo','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Metalbrow','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mezzaluna','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Miasma ','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mikmafy','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Minela','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Minenaga','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Minette','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Minotaur','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mio','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Moldus','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Morbeelzem','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MP Regen+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MP Regen+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MP Regen+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MP Regen+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MP Regen+7','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇MP+240','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mr. Jack','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mr. Obligaus','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mr. Oritius','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Mujie','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Muscle Tomato','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nepenth','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nero','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Neutral Enhancer I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Neutral Enhancer II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Neutral Enhancer III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nevin','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Niapa','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nigdu','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nimue','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ninigi','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nissa','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nuit','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Nuitram','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Obligaus','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Octocur','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ocypete','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Oritius','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Heal I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Heal II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Heal III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet HP I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet HP II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Magic I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Magic II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Magic III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Melee I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet Melee II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet MP I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pet MP II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Peyote','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Piton','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Plazuda','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Poison Boost I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Poison Boost II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pole','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Praldy','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇President Mezzaluna','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pretortoise','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Prince Arick','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Provoke','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pulis','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Pursuer','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Raguel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Raton','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Raynard','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Red Ogre','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Reflect I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Reflect II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Reflect III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Riddle Hatter','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Rita','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Roarmeria','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Rogelio','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ronden','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Rossam','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Rowell','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Rudolf','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Rusalka','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sakimori No Ryu','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sandwurm','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Santa Lady','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sauro','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sauro II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Schlingel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Scorpia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sea Muscle','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Seele Zauga','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Seele Zauga II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sharpness I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sharpness II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sharpness III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Shine burner','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Shining Varuna','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Shojo','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sianas','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sianas II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sierra Toropay','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sigrav','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Silvia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Simcracker','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Skarops','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Skill DT','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Smith''s Soul','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sofys','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Specia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Spector','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Spool','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Steiner','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Stormia','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR・INT+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&AGI+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&AGI+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&AGI+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&AGI+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&AGI+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&INT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&INT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&INT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&INT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&INT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&VIT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&VIT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&VIT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&VIT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR&VIT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇STR+7','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Strix','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Sturm','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Suigetsu','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Suishin','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Swallow','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Tailor''s Soul','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Tapicora','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Tarante','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Tarna','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Telon','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇The emptiness of forgetfulness','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇The shadow of the wandering','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Thothras','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Thrift I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Thrift II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Thrift III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Todel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Trial of Rock','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Tsuchinoko','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇UFO Luna','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Unicorn','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ur','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ushilth','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Valmut','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Vasaria','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Vatendeth','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Veleno Rosa','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Vida','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Vinz Zant','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&AGI+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&AGI+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&AGI+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&AGI+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&AGI+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&DEX+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&DEX+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&DEX+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&DEX+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT&DEX+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+1','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+2','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+3','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+4','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+5','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+6','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+7','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇VIT+8','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Viviana','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wargvel','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Warrior of Light','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Water Enhancer I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Water Enhancer II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Water Enhancer III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇White Fox','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇White Sun Flash','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇White Whale','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wind Enhancer I','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wind Enhancer II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wind Enhancer III','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wizaleon','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wizard','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wizard II','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Wyn','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Xeltysis','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Zant','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Ziddu','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Zimov','Crystas');
INSERT INTO `irunaitem` VALUES(NULL,'◇Zolban','Crystas');
COMMIT;
