
CREATE TABLE IF NOT EXISTS irunaitem
 (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'Alen''s Lexicon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ambition','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Amulet','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Amulet+','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Anti-Demon Mirror','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Anti-Demon Mirror (Strengthened 1)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Aprile Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Aprilis Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Archbishop Scepter','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ark Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Armandel','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Armandel Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Armandel Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Artemis Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'B・B・Q','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Barotas','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Barrier Dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Battle Mace','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Bishop Scepter','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Black Mage''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Black Wizard''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Blizzard Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Claw Candle Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Moon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Book of Thunder','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Branch to Another World','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Cane Candle Cane II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Cardinal Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caterina Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Charm','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Charm II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'choir wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'condensation wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Cotton Candy','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon (Strengthened 1)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hidden Powers','');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon (Strengthened 2)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon (Strengthened 3)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Curse Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dagger of Reflection','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book Vol. 4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Death List','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Deck Brush','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dinat Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Horn','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Earthquake Bell','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Earthquake Bell II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Empress Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Enhance rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Esprimere','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Esprimere II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Esprimere III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fast Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Feathered Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fire Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Flower Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book V','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book Vol. 4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forte Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fruru Revel','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fruru Revel II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Gato Negro','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'General Wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'General Wand II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'General Wand III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Glacier Wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Green Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Grimoire','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'hard stick cane','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Harpoon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hasakura Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Heal Branch','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Heal Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hermit Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hermit Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hex Aura','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'holy angel wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hurricane Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book Vol. 4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Invariance','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Joke Skull','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Judgement Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Kerykeion','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Kerykeion II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Kerykeion III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Laney Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Leek (Staff)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Leek II (Staff)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Lespolt Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Light Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Light Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Lotus leaf','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mace','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Machtrario','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Machtrario II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Machtrario III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Knife','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Knife II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Megistus Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Microscope','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'mirage dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod IAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod ILF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod IMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod IST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MC','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MP','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MR','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MS','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod PMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mortal Dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Necro Wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Neve Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ocean Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Paraxenos','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Petal Scream','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Phoenix Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Phoenix Staff II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Phoenix Staff III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Present Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Priest Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Princely Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Private Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Quake Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Queen Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Resolve Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Resty Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Resty Rod (Strengthened 1)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'rich staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ritual Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ritual Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ritual Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Royal Nectar','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sage Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Saint Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Saint Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Saint''s Scripture','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sandtester','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G1','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L5','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L6','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Savin Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'School Broom','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Snowman''s Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Solve Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Solve Rod+','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Solver Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sonic Hand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol.4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol.5','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Staff of Dawn','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Starlight Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Starter Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Storm Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Stroz Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Stroz Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Stroz Rod III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sunny Crystal','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sword Amulet','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sword Amulet (Strengthened)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sylph Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Talisman Sword','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tellas Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tellas Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Throat Knife','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Thunder Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tokoyo no Mihitaki','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Traveler Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Triaina','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Trident','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Trishula','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Trishula II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'True Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tsarita Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tuning Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Uber Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Universe','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Universe II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Universe III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Utsushiyo no Imibi','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vajra','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vajra II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Valida Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'VDA Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Velum Mace','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Venity Lily','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vouivre','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vouivre II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Water Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wing Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Knife','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wizard Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Cane','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Antidote','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Chana Masala','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Coagulant','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Cure Paralysis','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Energy Herb','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Eye Drops','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Mapo Dofu','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Merry Sweets','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Mikan Daifuku','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Moist Dirt','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Moss Manju','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Sirok','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Soybean Paste Soup','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Spice','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Spinnen Vaccine','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Stimulant','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Super Vaccine','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tandoori Chicken','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tear of the Moon','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tranquilizer','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Trial Vaccine','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tvorog','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Unread Fortune','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Bleed)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Blind)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Dizzy)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Fear)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Freeze)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Lethargy)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Paral.)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Poison)','Status');
COMMIT;
