
CREATE TABLE IF NOT EXISTS irunaitem
    (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'A Queen of the Night','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Ace Dealer','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Adler','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Adler II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Adler III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Air Slicer','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Air Slicer II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Air Slicer III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Air Slicer IV','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Artemis','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Artemis II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Artemis III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Artemis IV','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Knife ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Knife II ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Baselard','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Baselardo','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner Dagger ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner''s Dagger','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Boogala','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Boogala II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'calamity ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Centelleo','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Centelleo II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Chakram ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Chakram (Strengthened 1) ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Chakram (Strengthened 2) ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Chakram (Strengthened 3) ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Chalk','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'cowards blade ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Roar','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Diamante','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Don Gridare','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Roar','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Roar II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Roar III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Roar IV','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Eclipse','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Eventail','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Eventail II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Eventail III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fake Craft','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fake Craft II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fake Craft III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fake Craft IV','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Chakram','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Flabellum','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Flabellum II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Flabellum III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Flabellum IV','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fragarach','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fragarach II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fragarach III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Caim','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Caim II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fukumame squares ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fuma Shuriken','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fuma Shuriken II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fuma Shuriken III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Fuma Shuriken IV','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Garabestea','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Garabestea II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Garabestea III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Gift Box (Throwing) ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Gift Giver ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Glacier Kairi','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Halt Messer ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Halt Messer II ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Halt Messer III ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Hard Baselardo','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Higiri','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Hunter Knife','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Ice and snow throw ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Jade Luhi ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Jaeger knife','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Jagged Shuriken','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Jagged Shuriken II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Jagged Shuriken III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Jupiter','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Kagekiri','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Kunai ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Lime Dew','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Lime Star','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Lime Tear','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Lucani Tuela ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Lucanirafal ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Lucanivent','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Lucky Bean Box','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Luke Raider','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Luke Raider II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Eclipse','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mausoleum Forum ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mio Filio','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mio Filio II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw FAG','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw FLF ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw FMA ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw FST','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw GAG','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw GLF ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw GMA ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw GST','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw IAG','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw ILF ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw IMA ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw IST','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw SCR ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw SPI ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw SRE ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw SSP ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw TAG','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw TLF ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw TMA ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Throw TST','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Nirin Higiri ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Ocean Comet ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Oval of luck ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Owlmel','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Poisoned Knife','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Prescience','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Prescience II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Prescience III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Present Throw','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Private Throw ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Bomb','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Cross','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Raiju Jiulong 100 ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Raiju Jiulong 200 ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Red Wind ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Red Wind II ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Rogue Knife ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster G1','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster G2','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster G3','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster G4','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster L2','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster L3','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster L4','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Aster L5','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Savin Throw ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Seabeast Twin Irons ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Shikigami Yorishiro ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Slow gear ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Slow gear II ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Stavros','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Swimming Float','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Throwing Knife','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Throwing Knife+','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Toy Hoop','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'tribe axe ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Trivelos ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Tysrary ','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Uroboros','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Uroboros II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Whirlwind','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Wicktrace','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Wicktrace II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Wicktrace III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Xiphos','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Xiphos II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Xiphos III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Xiphos IV','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Zenebel','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Zenebel II','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Zenebel III','Throwing');
INSERT INTO `irunaitem` VALUES(NULL,'Adventurer Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Adventurer Garb','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Adventurer Garb (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Adventurer Garb (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Agile Garb','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Air of the Dark ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Air of the Dark (Strengthened 1) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Altoshear','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Altoshear (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Altoshear (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Altoshear (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Amartier','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Armadora','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Armadora (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Armadora (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Armadora (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Bellow of Order','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Bellow of Order (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Black Iron Armor ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Black Plate','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Black Plate (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Chainmail','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Chainmail (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Chainmail (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Chainmail (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Cleric Robe','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'counter mail ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Country Road','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Country Road (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'cursed mantle ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Damascan Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Priest Robe','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Priest Robe (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Priest Robe (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Priest Robe (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Deceiver','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Deceiver (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Mail','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Mail (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Mail (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Mail (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dragonskin Coat ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dunkelheit','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dunkelheit (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dunkelheit (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Dunkelheit (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Emido','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Emido (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Emido (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Emido (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Exelis','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Exelis (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Exelis (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Exelis (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'flower fair ava (Strengthened 1) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'flower fairy ava ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ghillie Suit','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Mail ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Mail (Strengthened 1) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Mail (Strengthened 2) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Heinrich Mail','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Heinrich Mail (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Heinrich Mail (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Holy Mail ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Brut','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Nemes','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Nemes (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Nemes (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Nemes (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Ries','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Ries (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Ries (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hulam Ries (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Hunters clothing ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Dragon Armor ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Idea Replica ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ira','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ira (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ira (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ira (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Armor (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Armor (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Armor (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Armor (Strengthened 4)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Laminated Mail','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Mail','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Mail (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Mail (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Mail (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Mail (Strengthened 4)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Leather Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Leather Coat','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Leather Coat (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Leather Coat (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Licht Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Licht Armor (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Licht Armor (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Licht Armor (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Linen Clothes','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Linen Clothes (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Linen Clothes (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Garb','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Garb (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Garb (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Garb (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Garb','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Robe','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Maid Outfit ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Maid Outfit (Strengthened 1) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Maid Outfit (Strengthened 2) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mana Tunic','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mereth','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail FAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail FLF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail FMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail FPI','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail FR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail FST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail GAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail GLF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail GMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail GPI','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail GST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail IAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail ILF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail IMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail IPI','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail IR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail IST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail RR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail TAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail TLF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail TMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail TPI','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail TR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Mail TST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe DMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe FAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe FCR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe FLF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe FMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe FS','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe FST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe GAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe GCR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe GLF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe GMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe GST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe IAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe ICR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe ILF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe IMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe IS','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe IST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe RS','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe TAG','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe TCR','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe TLF','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe TMA','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe TS','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Robe TST','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ossi Model','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ossi Model (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Pao','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Pao (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Pao (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Pao (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Parulian Uniform ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Parulian Uniform (Strengthened 1) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Parulian Uniform (Strengthened 2) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Plate Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Plate Armor (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Plate Armor (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Plate Armor (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Prisonnier','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Private Armor ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Private Clothes ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Red Bringer','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Rich Robe ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Sacred Robe','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Saltus','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Saltus (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Saltus (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Saltus (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Schwartz','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Schwartz (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Schwartz (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Schwartz (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Schwermer','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Schwermer (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Schwermer (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Seashells','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shiroito-Odoshi','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shiroito-Odoshi (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shiroito-Odoshi (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shiroito-Odoshi (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shushiwa Armor','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shushiwa Armor (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shushiwa Armor (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Shushiwa Armor (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Mail','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Mail (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Specia Costume ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Struggler','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Struggler (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Struggler (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Suigetsu Flower Dress ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Suigetsu Flower Dress (Strengthened 1) ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Tentacion ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Garb','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Garb (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Garb (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Garb (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Garb (Strengthened 4)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Timorier','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Traveler Garb ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Tunic','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Tunic (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Tunic (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Tunic (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ultimi','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ultimi (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ultimi (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Ultimi (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'venom prison ','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Weiss','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Weiss (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Weiss (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Weiss (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Robe','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yang Ninja Garb','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yang Ninja Garb (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yang Ninja Garb (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yang Ninja Garb (Strengthened 3)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yin Ninja Garb','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yin Ninja Garb (Strengthened 1)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yin Ninja Garb (Strengthened 2)','Armor');
INSERT INTO `irunaitem` VALUES(NULL,'Yin Ninja Garb (Strengthened 3)','Armor');
COMMIT;
