CREATE TABLE IF NOT EXISTS irunaitem
 (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'Angel Item','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Bernard Candy Bag','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Black Silver Feather','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Box','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Candy bag','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Dirty Magic Book','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Empty Vessel','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Bead','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'G. Power','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Chest','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Orb','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Jewel Box','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Lucky Bag: Ore','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Lucky Bag: Seed','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Lamp','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Octocur Candy Bag','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Old Treasure Box','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Ore box','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Dress Box','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Box A','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Box B','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Box C','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Box D','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Box E','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Orb A','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Red Box','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro''s Chest','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro''s Chest 2','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro''s Chest 3','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro''s Chest 4','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro''s Chest V','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro''s Gold Chest','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Snowflake Blessing','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Sweet Bouquet','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Treasure Box','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'White Silver Feather','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Present','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Disappeared Santa Sack','');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Present 2','Chests');
INSERT INTO `irunaitem` VALUES(NULL,'Aged Revita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Anko','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Apple','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Apple Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Bad Apple','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Bad Watermelon','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Bamboo Bottle','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Banana','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Banana au Lait','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Banana Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Basmati Rice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Bat Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Bean Curd','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Beautiful Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Beef','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Big Egg','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Big Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Binal (L)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Binal (M)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Binal (S)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Binal (XL)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Binal (XXL)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Black Bandage','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Black Gel Drink','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Black Jelly','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Blind Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Gel Drink','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Jelly','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Mushroom','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Boar Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Boat prime','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Boat-Wrap Sashimi','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Bread','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Bright Cacao','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Burnt Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Butter','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cacao','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Candy','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Candy Apple','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Candy Syrup','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Caozaiguo','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Carrot','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Century Egg','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cheese','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cherry','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cherry Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cherry Pie','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Chicken Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Chicken Nanban','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Chicken Orange Stew','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Classy Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Coconut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Coconut Water','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cola','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cooked Frog Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cooked Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cookie','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Crab Butter','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Crab Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Crab miso','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Crab Scissors','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cracked Mage Ore','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cream','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cream Puff','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cruel Evil Eye','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Cursed Evil Eye','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Daifuku','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Deep-fried Bean Curd','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Demi Hamburg Steak','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Diel Medicine','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'dizziness dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Liquor','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Stone','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Dried Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Dried Seaweed','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Edamame','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Egg','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Eggplant','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Ehomaki','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Collecting Ehomaki Ingredients','');
INSERT INTO `irunaitem` VALUES(NULL,'Elastic Bandage (Black)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Elastic Bandage (White)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Energy Drink','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Expert Potion','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Failed Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fancy Pet Food','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'fear dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Firecracker','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Firely Spicy Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fish Cheek','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fish Head','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Forisco Grass','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fortune Shrine Water','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fortune-telling Candy','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fresh Fish','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fresh Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fresh Red Fish Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fresh White Fish Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Frog Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Frozen Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fruit Compote','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fruit of the mushroom','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fruit Punch','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fruit Revita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Fukumame','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Gladiator Revita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Goddess Tear','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grace Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Bell Pepper','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Coca','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Corn','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Potato','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Tomato','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grape','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grape Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Griffin Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grilled fish','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Grilled White Meat Fish','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Ground Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Guild Remagic','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Guild Revita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Halloween Coin','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Hamburg Steak','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Handmade Choco','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Hard Egg','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Health Conversion','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'high KO dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'high poison dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'High-class Potion','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Hinomaru Bento','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Hot Revita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Inari Sushi','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Irunayaki','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Jelly Steak','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Keema Curry','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Kijimu Leaf','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Kijimu Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Kitsune Udon','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'KO Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Koya-dofu','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Large Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Leaf of Life','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Leather Canteen','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Leeds special chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Leek','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Lemon','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Lemon Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Life Fragment','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Life Oil','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Life Shard','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Life Soma','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Light Crystal','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Light Green Eggs','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Little Bean Pot','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Living Water','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Love Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Lucky Bean','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Lychee','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Jar (Cold)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Jar (Mud)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Jar (Pure)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Jar (Warm)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Soma','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mango Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Maple Tea','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Marshmallow','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Medical Herb','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Medicinal Morel','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Medirita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Melon','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Melon Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Milk','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Miracle Tea','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mirin','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mitarashi Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mizu-Yokan','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mushroom Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mysterious Herb','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Nissa Manju','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Nutty Creme','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Obligation Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Ochazuke','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Okonomiyaki','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Onigiri','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Orange','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Orange Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Osechi','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Paralyze Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Peppercorn','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pet Food','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pickled Plum','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pineapple','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pineapple Cake','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pineapple Jelly','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pineapple Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pizza','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Poison Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Poison Mushroom','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pork','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Potato','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Powder Snow','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Candy','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Juice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Pure Water','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Remagic','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Revita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Raisins','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Raw Egg of Life','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Red Cacao','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Red Meat Fish Zuke','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Regera (L)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Regera (M)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Regera (S)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Regera (XS)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Remagic (L)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Remagic (M)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Mana Wave 2','');
INSERT INTO `irunaitem` VALUES(NULL,'Remagic (S)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Remagic (XL)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Remagic (XXL)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Revita (L)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Berserk 1','');
INSERT INTO `irunaitem` VALUES(NULL,'Revita (M)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Revita (S)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Evil Santa','');
INSERT INTO `irunaitem` VALUES(NULL,'Revita (S)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Goddess Statue at the Mine','');
INSERT INTO `irunaitem` VALUES(NULL,'Revita (XL)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Revita (XXL)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Revita Ale','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Rice','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Rice and Curry','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Ripe Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Rita''s Test Medicine','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Roast bird','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sage Stone','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sake Gourd','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sake Steamed Clams','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sakuramochi','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Salt','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Salted Tongue','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Salty Leaf','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sashimi','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sauroin Steak','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sauteed Eggplant','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Scallops','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Scorpion Ale','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Scrambled Eggs','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Secret Source','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Shark Fin','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Slice of Cactus','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Snake Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Soft Cacao','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sorghum','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Soup Stock','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sour Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Soy Sauce','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Soybean Paste','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sp. Revita Ale','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sparkling Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Special Binal','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Special Regera','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Special Revita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Spicy Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Spicy Syrup','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Spinnen Energy Drink','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Spirita','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Stoic Seed','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Strange Fungus','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sugar','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sweet Chocolate','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sweet Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sweet Syrup','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Sweet-Sour Fruit','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Taiyaki','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Takoyaki','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tanuki''s Bottle','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tartar Sauce','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tasty Candy','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tasty Fish','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tasty Mushroom','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tasty Nut','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tasty Water','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tawa Chicken','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tenderloin Steak','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Thick Remagic (L)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Thick Remagic (M)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Thick Remagic (S)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Thick Revita (L)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Thick Revita (M)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Thick Revita (S)','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tomato','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tough Meat','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Treat Cookie','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Trick cookies','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Tricolor Dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Ultimate Carrot','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Umechazuke','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Unaju','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Unhulled Rice of Dawn','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Vinegar','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Watermelon','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'weakness dango','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Wheat Beer','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'White Bandage','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Whole Roast','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Witchcraft Cacao Beans','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Fish','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Bell','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Yakisoba','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Yogurt','Recovery');
INSERT INTO `irunaitem` VALUES(NULL,'Yu Dofu','Recovery');
COMMIT;