
CREATE TABLE IF NOT EXISTS irunaitem
 (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'Albedo Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Ale Keg','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Anvil','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Arched Bridge','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Arched Bridge Ab.','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bean Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bernard Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Blanc Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Block','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bronze Candelabrum','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Bronze Candlestick','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Brosch Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Chair','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Chako Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Colon Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Corn Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Eerie Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Field King Bust','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks A','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks B','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks C','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks D','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks E','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks H','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Fireworks I','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Flowerbed','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Flowerbed (L)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gemic Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Candelabrum','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Candlestick','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Colon Icon','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Cutlery','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Golden Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Carrot','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Napa Cabbage','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Radish','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Stump','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grandy Tomato Planter','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Grass Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Green Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Green Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Griffin Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Basalt)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Granite)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Jasper)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Obsidian)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Guardian Cat (Pyrite)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Halloween Tails Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Block','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Pillar','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Iris Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Rice Cooker','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Leek Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Maneki-Neko Altar','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Maneki-Neko Statue (S)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mani Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (A&T)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (D)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (G)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (M)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (T)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Memory Painting (V)','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mini Cactus','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mini Haniwa','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mini Snowman','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Miwi Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Moeba Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Mooth Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'New Year Deco.','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Nigredo Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Noah Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Octocur Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Okiri Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Oni Stone Lantern','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Pengino Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Piton Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Potted Plant','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Potted Tree','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Purple Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Rafflesia Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Red Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Red Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Rose Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Rowell Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Candelabrum','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Candlestick','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Cutlery','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Skull','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Slime Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Snow Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Snow Sculpture','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Snowman Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Stacked Bean Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Stacked Golden Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Stock Pot','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Table','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Tomato Kijimu Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Tri-Tail Doll','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wok','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Hand Pail','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Pail','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Poke','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Cake B','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Wreath','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Cushion','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Zabuton','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'ドンペン人形','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'ビーチルナ人形','IslandItems');
INSERT INTO `irunaitem` VALUES(NULL,'★ Altoale Sector','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Aqruf Town','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Caldera village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Elban','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Eldan','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Saterica','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Capital City Sofya','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dark Castle','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dark Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dark Santa','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Deeos village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Diel Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Divine Tower','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Dorry','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Drafbourg','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Earth Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Eryldan Desert','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Fire Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Food Storage','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Fort Bailune','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Ganaji Strand','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Heaven Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Histaria','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Ioleu Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Justice Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kakeula City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kilf Plains','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kleven Corridor','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kleya City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kreldan','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Kreya City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Leelids Field','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Lograth City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Lunite Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Lydia','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Maios','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Maldario','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Mawid Plains','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Maze of Enzeits','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Mercy Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Minaula City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Mioreita Castle','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Nidea coast','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Oltoga Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Orolhool','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Ouvels Chamber','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Peace Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Pilaneza City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Port Spargas','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Reoctove','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Rokoko City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Rokoko Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Roye Underground Church','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Rudolf','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Sateria City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Sauro Village','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Sofia Street','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Specia Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ special blacksmith','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Underground Bailune','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Upper Palace','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Varant Town','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ War Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Water Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Wibo City','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Wind Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Windstone','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Wisdom Key','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'★ Xaofks','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'Blank invitation','Teleport');
INSERT INTO `irunaitem` VALUES(NULL,'Isle Invitation','Teleport');
COMMIT;
