
CREATE TABLE IF NOT EXISTS irunaitem
 (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'Alen''s Lexicon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ambition','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Amulet','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Amulet+','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Anti-Demon Mirror','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Anti-Demon Mirror (Strengthened 1)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Aprile Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Aprilis Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Archbishop Scepter','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ark Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Armandel','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Armandel Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Armandel Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Artemis Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'B・B・Q','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Barotas','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Barrier Dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Battle Mace','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Bishop Scepter','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Black Mage''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Black Wizard''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Blizzard Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Claw Candle Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Moon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Book of Thunder','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Branch to Another World','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly Fan IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caduceus IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Cane Candle Cane II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Cardinal Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Caterina Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Charm','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Charm II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'choir wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'condensation wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Cotton Candy','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon (Strengthened 1)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hidden Powers','');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon (Strengthened 2)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Crescent Moon (Strengthened 3)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Curse Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dagger of Reflection','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Book Vol. 4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Death List','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Deck Brush','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dielita IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dinat Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Dragon Horn','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Earthquake Bell','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Earthquake Bell II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Empress Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Enhance rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Esprimere','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Esprimere II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Esprimere III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fast Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Feathered Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fire Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Flower Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book V','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forbidden Book Vol. 4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Forte Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fruru Revel','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Fruru Revel II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Gato Negro','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'General Wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'General Wand II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'General Wand III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Glacier Wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Green Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Grimoire','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'hard stick cane','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Harpoon','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hasakura Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Heal Branch','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Heal Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hermit Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hermit Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hex Aura','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'holy angel wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Hurricane Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Book Vol. 4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Invariance','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Joke Skull','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Judgement Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Kerykeion','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Kerykeion II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Kerykeion III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Laney Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Leek (Staff)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Leek II (Staff)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Lespolt Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Light Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Light Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Lotus leaf','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mace','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Machtrario','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Machtrario II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Machtrario III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Knife','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Knife II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Megistus Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Microscope','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'mirage dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod FST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod GST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod IAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod ILF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod IMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod IST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MC','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MP','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MR','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MS','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod MST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod PMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TAG','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TLF','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TMA','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Rod TST','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Mortal Dagger','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Necro Wand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Neve Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ocean Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Paraxenos','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Petal Scream','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Phoenix Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Phoenix Staff II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Phoenix Staff III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Present Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Priest Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Princely Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Private Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Quake Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Queen Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Raziel Code IV','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Resolve Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Resty Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Resty Rod (Strengthened 1)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'rich staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ritual Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ritual Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Ritual Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Royal Nectar','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sage Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Saint Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Saint Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Saint''s Scripture','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sandtester','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G1','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick G4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L5','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Stick L6','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Savin Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'School Broom','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Snowman''s Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Solve Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Solve Rod+','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Solver Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sonic Hand','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol. 2','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol. 3','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol.4','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Spell Book Vol.5','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Staff of Dawn','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Starlight Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Starter Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Storm Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Stroz Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Stroz Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Stroz Rod III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sunny Crystal','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sword Amulet','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sword Amulet (Strengthened)','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Sylph Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Talisman Sword','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tellas Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tellas Rod II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Throat Knife','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Thunder Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tokoyo no Mihitaki','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Traveler Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Triaina','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Trident','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Trishula','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Trishula II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'True Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tsarita Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Tuning Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Uber Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Universe','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Universe II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Universe III','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Utsushiyo no Imibi','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vajra','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vajra II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Valida Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'VDA Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Velum Mace','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Venity Lily','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vouivre','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Vouivre II','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Water Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Dragon Staff','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wing Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Knife','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wizard Rod','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Wooden Cane','Canes');
INSERT INTO `irunaitem` VALUES(NULL,'Antidote','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Chana Masala','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Coagulant','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Cure Paralysis','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Energy Herb','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Eye Drops','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Mapo Dofu','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Merry Sweets','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Mikan Daifuku','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Moist Dirt','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Moss Manju','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Sirok','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Soybean Paste Soup','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Spice','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Spinnen Vaccine','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Stimulant','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Super Vaccine','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tandoori Chicken','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tear of the Moon','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tranquilizer','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Trial Vaccine','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Tvorog','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Unread Fortune','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Bleed)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Blind)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Dizzy)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Fear)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Freeze)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Lethargy)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Paral.)','Status');
INSERT INTO `irunaitem` VALUES(NULL,'Vaccine (Poison)','Status');
INSERT INTO "irunaitem" VALUES(NULL,'A rare enhancer','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'A tonic of another world','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Academy Protein','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Accuracy Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Akashiyaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apatite','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apple Jam','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apple Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apple Meuniere','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apple Pie','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apple Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apple Tart','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Apple Tea','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Aroma Potpourri','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Attack Contract 1','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Aui Knight','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Bacon','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Bacon and Eggs','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Bacon Potato','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Bacon-wrapped Sprout','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Baked Honey Banana','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Baked Potato','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Banana Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Basket','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Beautiful Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Beef jerky','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Big Whetstone','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Bitter Nut','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Black Hunter Candy','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Blinchiki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Blood Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Blue Candy Bag','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Boar Stew','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Boiled Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Boiled Edamame','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Boiled Egg','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Boiled Leaves','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Brainy Potion','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Braised Venison','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Brawny Potion','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Caesar Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Canapes (Fish)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Canapes (Meat)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Candy Floss','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Carbonated Water','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Carrot Cake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Carrot Saute','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Castella','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cephalopod Ink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Charred Newt','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cheese Fondue','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cheese Potatoes','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cheesecake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cherry Cake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cherry Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Chicken Wing','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Chicken&Egg Bowl','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Chikuwa','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Choco Colon','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Chocolate Milk','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Christmas Bell','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Classy Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Clear Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Coconut Cake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Coconut Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Coleslaw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Colon Tea','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Consomme','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cooked Corn','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cooked Filet','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Copper Lantern','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Corn Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Corn Soup','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cornflakes','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Crab Cream Croquette','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Crab Fried Rice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Crepe','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Croquette','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Crunchy Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Cucumber','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Curry Bread','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Curry Powder','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Custard Pudding','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Daifuku ice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dark bottle','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dark Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dark Iron Claw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dark Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dark Red Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Demi Omurice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Demi-glace Doria','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Devil Medicine','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Disposable Claw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dizzy Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Domino','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Donpen Cookie','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Donpen Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Doria','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dotenabe','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dried Gourd','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dried Squid','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Dull Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Earth Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Earth Iron Claw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Eclair','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Edamame Soup','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Eel','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Eel Sauce','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Eerie liquid','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Egg Burger','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Egg Tart','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Evasion Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Exociser Cacao Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fear Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fearful Evil Eye','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fire Cocktail','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fire Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fire Iron Claw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fire Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fish Meuniere','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fish Pie','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fish Saute','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Flint','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Food Contract 1','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Forbidden fruit','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fortune Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Freeze Cocktail','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'French Fries','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fried Chicken','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fried Chicken Ball','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fried Rice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fried Takoyaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Frosted Curio','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Frozen Meat','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Fruit Granola','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'German Potato','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Gold Lantern','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Golden Pound','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Grape Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Grated Radish','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Gratin','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Greenish Meat','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Grilled Eel','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Grilled Mushroom','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Grund Stew','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Gyoza','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Gyudon','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Ham','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Ham Cutlet','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Ham Marinade','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hamburger','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hayashi Rice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hazardous Herb','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Herb Rice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'High-Grade Meat','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hiroshimayaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Honey Milk','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Honey Soaked Lemon','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Honey Toast','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hot Cake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'HQ Wooden Clapper','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hustle Tomato','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hydrangea Dye (Green)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hydrangea Dye (Pink)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Hydrangea Dye (Purple)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Ice Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Icecream','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Ikizukuri','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Irresistible trap','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Itadaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Jack o'' Lantern','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Joulutorttu','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Juicy Skewers','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Kakkonto','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Kijimu''s Eel Lunchbox','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Kinshi Tamago','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Lantern','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Lemon Cake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Lemon Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Lemon Pie','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Lemon Tea','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Lens Tube','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Light Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Light Iron Claw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Little Calm Bell','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Lograth Treasured Liquor','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Macaron','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Magic Guard Rune','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Magic Horn','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Magic Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Makani tea','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mango Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Maple Parfait','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Maple Sugar','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mayonnaise','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Meat Roll','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Meaty Pasta','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mefun','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Melon Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Melon Pie','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mini Taiko','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mixed Sandwich','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mizutaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mochi Ice Cream','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mochi Kinchaku','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Modern-Yaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mokkaparat','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Monjayaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mousse','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mushroom Saute','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'mushroom soba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mysterious Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Mysterious Nut','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Navel Cocktail','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'New Year Soba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Nikujaga','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'No-Bake Cheesecake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Nut Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Octopus Tentacle','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Oden','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Omelette','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Omurice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Onion Beef Sinew','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Orange Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Palm Wine','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Paralysis Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Parfait','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pilanezan Wine','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pink Heart Bouquet','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pithiviers','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Poison Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pork Bowl','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pork n'' Plum Paste Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Potato Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Power Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pretty Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Promise Ring','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pudding','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pulla','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pumpkin Cake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Pumpkin Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Purification Cacao Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Quick Evil Eye','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Radio-Yaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Raisin Bread','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Rapum Rice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Raw Ham and Melon','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Red Bracelet of Fate','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Red Candy Bag','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Red Gel Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Red Jelly','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Red Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Reflection System','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Reflex Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Rib Steak','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Roast Chicken','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Runebergintorttu','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sachertorte','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sakura Denbu','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sakura Leaf Tea','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Salad Oil','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Salt Steamed Chicken','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Salt Yakisoba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Scarlet beryl','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Schnell Cocktail','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Seafood Gratin','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Seafood Yakisoba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sekihan','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Shallow sea poison bag','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Shark Fin Soup','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Shaved Ice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Shiitake','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Shikomi Shuriken','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Shikomi Shuriken+','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Silver Lantern','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Small Whetstone','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Smart Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sorrowful Eye','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Soy Sauce Yakisoba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Spare Rib','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Special Okonomiyaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Special Takoyaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Special Vita Plus','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Special Yakisoba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Spiky Potato','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Spinnen Prescription','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Squid Tentacles','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Squid with Chili Sauce','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Stationery Set','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Steamed Egg Custard','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Stew','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Stollen','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Strange Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Strength Contract 1','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Strongest Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sublime Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sukiyaki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Blood Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Dark Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Dizzy Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Dull Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Fear Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Fire Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Hard Candy','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Ice Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Paralysis Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Super Poison Oni Beans','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sushi (Egg)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sushi (Fish)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sweet and Sour Pork','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sweet Bean Paste Bun','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Sweet Potato','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Swiss Roll','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Syrniki','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Taco Rice','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Tantan Noodles','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Tasty Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'tempura soba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'ten percent soba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'The corner boiled deer meat','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'The ultimate dish','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Thick Omlet','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Tomato Burger','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Tomato Salad','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Top secret recipe','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'tororo soba','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Tough Skewers','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Tuna','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Tuna Sandwich','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'twice-cooked pork','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Ultimate cup','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Unknown Fruit','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Unrolled Sushi','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Vegetable Soup','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Velocity Pill','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Vinegared Octopus','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Vita Plus (L)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Vita Plus (M)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Vita Plus (S)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Waffle','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'War Guard Rune','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'War Horn','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Water Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Water Iron Claw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Weird Candy','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Whetstone','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'White Heart Bouquet','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'White Phosphorus','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'White Popsicle','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'White Wolf Candy','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Wind Drink','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Wind Iron Claw','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Wine','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Wonderful Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Wooden Clapper','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Workout Gift','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Yakitori','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Yellow Candy Bag','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Yellow Heart Bouquet','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Zodiac Talisman (Dragon)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Zodiac Talisman (Horse)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Zodiac Talisman (Monkey)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Zodiac Talisman (Rooster)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Zodiac Talisman (Sheep)','Strengthening');
INSERT INTO "irunaitem" VALUES(NULL,'Zodiac Talisman (Snake)','Strengthening');
COMMIT;
