
CREATE TABLE IF NOT EXISTS irunaitem
    (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,' Anostail','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Abandon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Abyss Guard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Abyssal Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Achu Rinbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Adel Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Adel Mask (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Adel Mask (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Adventurer Big Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Aerugo Green Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Aldoor','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Alen''s Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Almas Brimas','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Altorm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Altorm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Altorm (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'amber crowns','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Amerityara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Amrivelt','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ancient Helmet','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Angel Raiment','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Angel Ring','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Anniversary Brooch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Antos','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Aoitsuki Noriyuki helmet','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Arbus Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Arbus Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Arbus Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Archer Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ardour Cachenez','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Arelta','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Arelta (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Arelta (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Arm Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Armaresteca','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Asad Plate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Asad plate (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Asad Plate (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Asterios','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Asura Stole','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Asura Stole (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Asura Stole (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ateru ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Athame','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Attica','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Attica (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Attica (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Attica (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Audlus','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Audlus (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Augur Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Auler','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Auler (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Auler (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Aulis Blast','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Aulis Gale','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Aureola of Dawn','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ayaigasa','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'B flog cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'B-Wing','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bae Rokyan','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bandana','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Baphomet Horn','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Barbarotita','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Barbarotita (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Barbarotita (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Barbarotita (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bardrick','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bardrick (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Battle Surcoat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Battle Surcoat (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Beard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Beard (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Beast Howl','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Beast Howl (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Beautiful Crown','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Benefis','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Benefis (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Benihisago','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Benite Horns','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'biere ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bird on Head','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bishop Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bishop Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bishop Hat (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Band','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Barrette C','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Barrette L','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Barrette R','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Bunny Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Cat Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Cat Hood (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Cat Hood (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Cat Set','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Cat Set (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Dahlia','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Dahlia (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Glasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Black Twin Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blancheur','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blancheur (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blancheur (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blessed Tiara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blocachnez','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blossom Hairpin','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blossom Hairpin (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Barrette','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Belt ','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Bunny Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Epaulette','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Glasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Ogre Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Twin Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Blume Gift','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Booster','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Booster (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Booster (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Booster (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bottom Gift','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Braid Headband','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brave Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brave Cape (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brave Cape (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brave Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brave Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brave Shield (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Breezy Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brim Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Brim Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bronze Round Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Buckler','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Buckler (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Buckler (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Buckler (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bunny Ear Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bunny Ear Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Bunny Ears','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Butterfly wings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cactus Chignon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cactus Chignon (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Caesar Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cake Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Carib Horns','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Carmo Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Carmo Hood (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Carmo Hood (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Carol','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Casquette','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Casquette (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cat Ears','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cat Neck Pouch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cat Set','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cat Set (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cataract Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Charlotte Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Chase Cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Chase Cap (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Chase Cap (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Chignon Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Chocolate Banana','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Chonmage','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Christmas Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ciel','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ciel (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ciel (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cilwa Cross','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cilwa Cross (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Clematis','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Clematis (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cloak','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cloak (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cloak (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Collector Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Colon Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Colon Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Colon Pouch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Conversion Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Corona Vasilisa','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Crabjiro','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Crabtaro','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Crabzaburo','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Crimson Eyepatch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cross Earrings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Crown Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Crown Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Crystal Halo','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cuirass','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cuirass (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cuirass (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cunicle','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cunicle (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Cunicle (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'curl-luns','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Daiginjo [Holiday]','Holiday Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Daiginjo [Holiday] (Strengthened)','Holiday Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Headguard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Headguard (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Headguard (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Red Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Wings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Darkness frills','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Darkness Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Day Pack','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Day Pack (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dentelle Tiara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Deux Plantes','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Deux Plantes (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Devil Feather','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Devil Feather (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Devil Horn','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Devil Horn (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Devil Horn (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Diamond Tarot','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Diamond Tarot (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Diamond Tarot (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Diol Plate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Divergence Sword','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Divergence Sword (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Doggy Ears','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Doggy Ears (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Doggy Ears (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Doggy Ears (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dojigiri','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dragonchild''s Gift','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Druj Plume','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Duel Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Duel Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Duel Shield (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Duel Shield (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Dustpan','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Earmuffs','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Earmuffs (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ecarlate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Edel Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Edel Hood (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Edel Hood (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'El Blenen','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Elflamme','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Elven Cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Elven Cap II','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Emisul Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Emisul Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Emisul Helm (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ensis Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ensis Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Epaulettes','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Epaulettes (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Epaulettes (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Epaulettes (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Euto Pisol','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Evil Dragon Wings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Evil Dragon Wings (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Eye Bandage','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Eye Bandage (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fae Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fae Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fae Shield (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Failwind','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen Angel Wing','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Crown','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Farfalla','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Farfalla (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Farfalla (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Farmer Belt','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Farmer Belt (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Farmer Belt (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fel Epaule','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fencer Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fighter Gauntlet','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Blazon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Floral Corona','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Foehn','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fond Guard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Force Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Force Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Force Helm (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Force Helm (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fourchette','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fourchette (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fourchette (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fox Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fox Scarf (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Fox Scarf (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Frankenstein Bolt','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Frankfurter','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Freeze Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Frog cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Garde Scythe','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gem Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gem Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Geo Cucule','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gewitter','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gewitter (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gewitter (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ghillie Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ghost Ring','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ghost Ring (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Girls'' Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Glass Tiara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gloire','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gloire (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gloot','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gloot (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gloot (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Glory Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Glory Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gluck','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gnade Tail','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Godchild Earwings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Goggle Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Goggle Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Goggle Hat (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gourd','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gourd (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grace Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grace Hood (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grace Hood (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Granvia Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Guard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Guard (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Guard (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gratia Helm (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grecia Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grecia Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grecia Helm (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Green Cat Ears','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Green Glasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Green Gourd','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Green Hydrangea Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Green Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Green Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Green Twin Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grim Reaper','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Grim Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Gutsy Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hachigane (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hachigane (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headband','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headband (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headband (Strengthened1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headgear','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headgear (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headgear (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headguard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headguard (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Headguard (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Heavy Plate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Heavy Plate (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Heavy Plate (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hermies','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hero Crown','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hibiscus','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hibiscus (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hibiscus (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Honor Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hoplon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hoplon (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hoplon (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Horned Helmet','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Horned Helmet (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Horned Helmet (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Horned Helmet (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Horse Horn and Wing','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Horse Horn and Wing (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hot-Blooded Headband','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Huge Cherry Blossom','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Huge Cherry Blossom (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hunter Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hunter Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hydrangea Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hydrangea Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Hyrik Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Iblis Plate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Iblis Plate (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Iblis Plate (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Dragon Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Spirit Tippet','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Spirit Tippet (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Idea Sham','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Idealsol','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Inari Scroll','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Itiance','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Itiance (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Itiance (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Jellyfish Water Crown','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Jujube Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Justice Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kabuto Noriyuki crescent','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kagamimochi Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kanzashi','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kanzashi (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kanzashi (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Karonamuska','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Karonamuska (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Karonamuska (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'King Dragon Necklace','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'King Dragon Necklace (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Knight of Honor','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Komodo Pocket','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Komodo Pocket (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Komodo Pocket (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kontramel','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Krish Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kukka Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kukka Cape (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kukka Cape (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Kukka Cape (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'La Mer Crown','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lacus','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lacus (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lacus (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Guard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Guard (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lava Guard (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Leaf Poncho','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Legion Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Legion Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Legion Helm (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Libersona','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Libersona (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Liebe Tail','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Light Blue Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Light Bulb','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lightning Feather Robe','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lion Dance hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lion Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lion Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lion Shield (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lion Shield (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lira Turban','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Little Wing','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lobelia Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lollipop','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lotus Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luanova Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lucioscudo','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lucioscudo (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lud Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Lud Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luludi','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luludi (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luludi (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Epaulette','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luna Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luxe Cloak','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luxe Cloak (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Luxe Cloak (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mad Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mage Fighter Cloak','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Hood (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Magia Hood (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Scroll','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Scroll (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Magic Scroll (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mahara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mahara (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mahara II','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Maid Headdress','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Maid Headdress (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Maid Headdress (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Maid Headdress (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mameshiba Head','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mameshiba Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mare','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mask of Collapse','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Masquerade','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Masquerade (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Masquerade (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Medic Pouch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Medim Corona','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Medim Corona (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Medim Corona (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mercure','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mercuria','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mir Symbol','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Miselatis','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Miselatis (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Miselatis (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Miwi Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Miwi Hat II','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Montol Colliet','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Montol Colliet (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Montol Colliet (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Monty Beret','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Monty Beret (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mortal Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mysterious Wind-up','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Mystic','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nacht Krone','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nasturtium','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Necky Backpack','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Necky Ears','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nejimaki','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nightcap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nightcap (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nightmare''s Love','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Noc','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nocros Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nocros Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Noir','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Noir (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Noir (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Nokkari Sabobon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'noodles','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ogre Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Oni Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Oni Hachigane (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Oni Hachigane (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Oni Hachigane (Strengthened 3)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Oni Sealing Belt','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Onigawara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Onigawara (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Onigawara (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Onimaru','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Orange Goggles','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Orange goggles (Strengthened 1)€#128247;','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Origami Kabuto','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'P flog cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pale Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pale Scarf (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pale Scarf (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Passion Robe','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Penguin cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Phalanx','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Phoenix Feather','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pieny Wings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pierrot Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pierrot Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pink Bunny Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pink Headband','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pink Hydrangea Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pink Moth Wing','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pink Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pink Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pink Twin Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pipe','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pipe (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pipe (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pirate Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pirate Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Piton Bag','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Piton Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Plaster Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Polar Bear Backpack','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Polar Bear Backpack (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Posession','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Prank Bucket','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pratzen','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pratzen (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pratzen (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Present Bell','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Prima Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Prima Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Prior Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Private Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Private Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Private Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Purple Cat Ears','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Purple Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Queen B','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Quick Ring','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Quiver','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'R flog cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Spear','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Raid Spear (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rain Fel','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rainy Day Bolero','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rear Lance','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rear Lance (Strengthened) ','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rebel Bandanna','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rebel Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rebel Hood (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rebellion Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rebellion Mask (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rebellion Mask (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Reckless','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Reckless (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Reckless (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Recuerdo','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Recuerdo (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Barrette','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Barrette F','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red barrette L','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red barrette R','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Barrette T','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Bunny Hood','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Bunny Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Glasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Headband','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Invader','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Red Twin Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Reincarnation Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Reincarnation Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Renegade','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Renegade (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Replica Gauntlet','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ribbon of Birth','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Ribbon of Resurrection','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rich Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Roof scan ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rosa de Amor','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rosa de Amor (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rose Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Roses Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rosso belt','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Rutla Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sablem','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sablem (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sablem (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sage Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sage Hat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sage Hat (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sandstorm Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Santa Beard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Santa Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Santa Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Santa Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Saphis Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Satan Wings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Scalpello','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Scarlet Glasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Scarlet Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Schlacht Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Schmuck','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Schmuck (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Schmuck (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'School cap','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Schulter','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Schulter (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Schulter (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Scroll case','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'seaney ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sector Plaster','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sector Plaster (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sector Plastor (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Seed Tiara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Separation Arrow (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Separation Arrows','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Shinobi Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sieger Plate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Silkhat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Skeleton Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sky Core','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sky Core (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Small feather','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Snow Earmuff','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Snow Wimple','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Snowflower Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Snowman Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Snowman on Head','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Snowman on Head (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sofys Glasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sofys Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sofys Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sofys Shield (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sofys Spectacles','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Solid Plate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Solua Coat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Solua Coat (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Solua Coat (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sorceris','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sorciere','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sorciere (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sorciere (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Soul Eater','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Soyl Tiara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Special Nyanko set','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Spirit Plume','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Spooky Cloth','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'sprite feathers','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Spy Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Spy Mask (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Starry Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Stella Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'sticking sabobon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Stier','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Stier (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Stier (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Streamer','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Streamer (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Suishin Katana','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Suishin Katana (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sulvan Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sulvan Mask (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sunflower Pin','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sunflower Pin (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sunflower Pin (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sunglasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Sunglasses (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Surface of demon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Survival Pouch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Taenia Beret','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Taenia Beret (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Terra','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'The Light Blue','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Bandana','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Bandana (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Bandana (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Tiara','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Tomato Head','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Topknot (Strengthened)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Totapon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Traffic Cone Head','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Trash Box (Blue)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Trash Box (Gray)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Trash Box Lid','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Travel Pouch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Travel Pouch (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Travel Pouch (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Travel Sack','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Travel Sack (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Tri-Tail','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Tri-Tail (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Tri-Tail (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Triangle Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Tricky Bandana','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Turban','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Twin Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Unity Symbol','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Vampal Tune','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Vanregal','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Variant','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Variant (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'VDA Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'VDA Mask','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Verde ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Vind Krone','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Viola','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Violin','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Voluntas','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Voluntas (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Voluntas (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'w-wing','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wakizashi','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wald Guard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'War Flag','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White barrette C','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Barrette W','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Bunny Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Cat Set','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Cat Set (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Maid Headdress','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Maid Headdress (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'White Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Dragon Wings','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wind-up Key','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wind-Up Key II','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wisdom Bag','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wisdom Bag (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wisdom Bag (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wisdom Crown','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wise Beard','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Eyepatch','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Eyepatch S','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Pumpkin Hat','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wizard Hachigane','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wolf Ears','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wolf Ears (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wolf Pup Chapeau','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wrath Rebate','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wrath Rebate (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wrath Rebate (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wroth Helm','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wroth Helm (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Wroth Helm (Strengthened 2)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Xmas Blue Cape','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Bunny Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Glasses','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Headband','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Plait R','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Scarf','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Twin Ribbons','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Zephyr Raiment','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Zsolt ribbon','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Zweig Shield','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Zweig Shield (Strengthened 1)','Additional');
INSERT INTO `irunaitem` VALUES(NULL,'Zweig Shield (Strengthened 2)','Additional');
COMMIT;
