CREATE TABLE IF NOT EXISTS irunaitem
 (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'2-Bladed Halberd','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Accord Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Adventurer''s Knife','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Air Strum','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Air Strum II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Air Strum III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ama no Habakiri','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ama no Habakiri II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ama no Habakiri III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ama no Habakiri IV','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Amethystia','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Angel the Shisui Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Aroundight','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Assassin Dagger','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Auroras Sword II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Avenir','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Avenir+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Balmung','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Barbaro Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Barbaro Axe II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Barbaro Axe III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Bardiche','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Bastard Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Bastard Sword+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Bastion','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Battered Weapon','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Battle Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Beginner''s Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Black Lacquer Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Black Lacquer Sword II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Black Lacquer Sword III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Blessed Blade','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Blessed Blade (Strengthened 1)','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Blood Roar','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Blood Ruler','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Blood Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Bloody Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Bloody Thorn Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Moon Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Boss Claymore','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Brace Pasimo','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Broom','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Butcher','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Caliburn','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Claiomh Solais','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Claiomh Solais II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Claiomh Solais III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Claymore','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Claymore+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Cortege','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Cosmic Dust','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Cosmic Dust II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Cross Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Crystal Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dainsleif','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dainsleif II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dainsleif III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Damascan Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Death Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Demon Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Demon Axe II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Demon Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Demon Scythe II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Desperado','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dhampir','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dia Espada','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dia Espada (Strengthened 1)','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dialan Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dim Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dim Sword II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dim Sword III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dim Sword IV','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Dim Sword V','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Diva Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Divine Punishment Club','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Divine Punishment Club II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Edge','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'El Avenir','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Emerald Roar','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Emerald Roar II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Enorme Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'epe wenwell','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Eraser','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Etincelle','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Excalibur','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Excalibur +','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Exile Dual Blades','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Fairy Tale World Spoon','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Fairy Tale World Spoon II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Fake Excalibur','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Fallen God''s Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Falx','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Fide Espada','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Firebrand Vritra','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Firebrand Vritra+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Swallow','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Flame Swallow II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Flashing Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Floor Squeegee','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Freesia Sword II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Fudo Myoo Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Fuguhiki Knife','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Futsu no Mitama','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'ga borg','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Genius','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Giblekening','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Glacier Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Gladius','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Glaive','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Glaive (Strengthened 1)','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Rex','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Rex II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Rex III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Good Bug Net','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Gram','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Grand Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Great Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Great Halberd','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Halberd','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Handaxe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Hauteclaire','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Heavy Broad Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Helshaft','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Hexe Espada','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Hexe Espada (Strengthened 1)','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'High Bastard Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Hihiiro Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Himekazu one letter','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Hirasaka the Soul Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Horror Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ice Brand Eisen','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Icebrand Rime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Icebrand Rime+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ichimonji','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Indra','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Inslector','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Iron Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Izuminokami','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Izuminokami II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Jade Ricus','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Katana','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Katzbalger','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Katzbalger II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Katzbalger III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Kloff Pillar','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Knight Espada','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Kotetsu','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Kukuri-hime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Kutune Sirka','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Kutune Sirka II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Kutune Sirka III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Laevatein','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Lamia','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Lamia II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Lamia III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Lamia IV','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Lebenglanz','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Leek (Sword)','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Leek II (Sword)','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Legacy of Will','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Legacy of Will II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Lion King''s Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Longblade','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Longsword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ludus','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ludus (Strengthened 1)','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Lumikening','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Magoroku','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Makaftir','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Masamune','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Masamune Shinuchi','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Men''s Umbrella','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mercenary Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Merculm ','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Merculm II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Merculm III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mercurius','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Merrow','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Millionaire Rapier','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mio''s Katana','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword FAG','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword FLF','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword FMA','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword FST','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword GAG','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword GLF','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword GMA','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword GST','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword IAG','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword ILF','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword IMA','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword IST','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword MCR','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword MPI','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword MRE','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword MSP','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SAG','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SC','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SLF','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SMA','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SP','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SR','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SS','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword SST','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword TAG','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword TLF','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword TMA','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mirror Sword TST','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Modern Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Moon Scimitar','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Moon Scimitar II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Muramasa','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Muramasa Shinuchi','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Murasame','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Murasamemaru','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mushroom Spada','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Nenekirimaru','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Niente','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Nigrum','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Nihil Espada','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Nilm','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Nio Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Normal Bug Net','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Ocean Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Orichal Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'outrange','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Pale Reaper','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Penetrator','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Penlight','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Pike Tomahawk','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Piper Mercy','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Piper Pieta','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Plastic Umbrella','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Pole Firebrand Vritra','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Pole Icebrand Rime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Present Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Private Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Pumpkin Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Punishment Warhammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Real Espada','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Reaper Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Red Tengu','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Red Tengu II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Red Tengu III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Red Tengu IV','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Rime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Rock Sword Helshaft','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Rock Sword Valten','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sacrifice','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sakuya-hime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sashimi Knife','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade G1','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade G2','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade G3','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade G4','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade L2','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade L3','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade L4','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade L5','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sauro Blade L6','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Savin Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Scimitar','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sea Breeze','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sea Breeze II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Seoritsu-hime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'seriously samurai','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Shamshir','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Shamshir+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Shinatsu-hime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Shirasaya','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Shitateru-hime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Shortsword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Shortsword+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sinbad','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sinbad II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sinbad III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sinbad IV','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Sinbad V','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Spiel','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Stampede','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Starter Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Stolie Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Telas Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Telas Scythe II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Thief Dagger','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Thunder Blade Indra','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Thunder Blade Indra+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Thunder Emperor Indra','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Thunder Emperor Indra +','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Tomahawk','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Torn Bug Net','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Toy Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Traveler Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Tree Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'True Firebrand Vritra','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'True Icebrand Rime','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Tsukuyomi','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Two Handed Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Tyrant Sword','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Tyrfing','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Valverna','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Valverna II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Valverna III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Varietta','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Vermilion','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Vermilion II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Vermilion III','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Vermilion IV','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Vigan Scythe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Violin Bow','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Vritra','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'War Axe','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Wespel','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Wespel II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'White Luna','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Witch Pumpkin Hammer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Wound Trance','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Wound Trance+','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Wound Transer','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Yanagiba Knife','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Zanbato','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Zanbato II','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Zwei Hander','Swords');
INSERT INTO `irunaitem` VALUES(NULL,'Aerial','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Bead Crystal','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Bead Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Black Gem','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Black Raw Stone','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Gem','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Blue Raw Stone','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Brass','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Clear Blue Ore','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Copper','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Copper Ore','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Damascus Steel','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Alloy','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Bead','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Dark Jewel','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Bead','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Earth Jewel','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Fire Bead','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Fire Jewel','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Gnome','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Gold','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Dust','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Nugget','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Ore','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Gold Pebble','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Green Gem','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Green Raw Stone','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Hematite','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'High Mythril','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Hihiirokane','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Iron','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Light Bead','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Light Jewel','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Lukia','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Mythril Ore','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Old Dark Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Old Earth Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Old Fire Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Old Light Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Old Memory Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Old Water Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Old Wind Fragment','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Orichalcum','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Orichalcum Ore','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Platinum Ore','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Red Gem','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Red Raw Stone','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Rock','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Salamander','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Shade','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Silver','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Silver Ore','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Undine','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Water Bead','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Water Jewel','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'White Gem','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'White Raw Stone','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Bead','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Wind Jewel','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Wrought Iron','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Gem','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Yellow Raw Stone','Ores');
INSERT INTO `irunaitem` VALUES(NULL,'Zinc ore','Ores');
COMMIT;
