
CREATE TABLE IF NOT EXISTS irunaitem
 (id int primary key AUTO_INCREMENT, name text, category text);
INSERT INTO `irunaitem` VALUES(NULL,'▲10th Anniversary','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Absolute Evasion I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Absolute Evasion II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Absolute Evasion III','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Adventurer','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲AGI+1','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲AGI+2','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲AGI+3','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Alan','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Almas','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Altan','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Anis','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Arick','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Aufsea','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Barbad','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Behemoth','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Bergen','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Bernhardt','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Biflog','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Blaiard','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Blank','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cast Defense I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cast Defense II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲casual storm','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cerbera','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cheltil','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cherose','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cooperin','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cordal','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Cordal II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲CRT+1','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲CRT+2','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲CRT+3','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Death Chils','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲DEF+100','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲DEF+150','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲DEF+50','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲DEX+1','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲DEX+2','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲DEX+3','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Douin','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Dunkelis','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Dym','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Earth Element II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Eldas','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Enina','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Enina II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Fiona','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Flame of mission','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Flammel','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Freedos','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Gadave','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Gan Ceann','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Gate Guard','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Gatekeeper','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Gauchel','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Giant Ape','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Glabora','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Green Morphy','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Gun Ryu','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Halios','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Heal Recovery I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Heal Recovery II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Heal Reward I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Heal Reward II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲HP Recovery +3%','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲HP Recovery +6%','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲HP Recovery +9%','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲HP+200','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲HP+400','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲HP+600','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Ibrie','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲ice of the life','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Ignatz','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Igro','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲INT+1','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲INT+2','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲INT+3','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Irai','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Jahoel','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Jinami','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Joshuca','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Jusal','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Kagen','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Katafnia','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Kotoamatsu','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Larkas','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Leviam','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Lunange','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Maelriel','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Magic Evasion I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Magic Evasion II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Magonza','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Malti','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Mamionette','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Mamonea','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Mani','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MDEF+100','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MDEF+150','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MDEF+200','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Medona','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Meelis','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Meligia','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Merario','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Metal Sauro','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Minela','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MP Cost -3%','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MP Cost -6%','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MP Recovery +3%','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MP Recovery +6%','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MP+120','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MP+180','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲MP+60','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Muscle','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Neutral Resistance II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Nimue','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Obligaus','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Octocur','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Orin','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Oritius','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Ouvel','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Parazaia','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Pauk','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Pole','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Queen Fugue','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Range Cut I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Rate Damage Cut I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Rate Damage Cut II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Reflect II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Reflection I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Dark I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Earth I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Fire I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Light I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Light II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Neutral I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Water I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Resist Wind I','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Rita','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Rua','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Rua II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Rufaty','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Sakimori No Ryu','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Sauro','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Sauro II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Sauro III','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Seele Zauga','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Seele Zauga II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Shelk','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Sofys','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Specia','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Spikeleon','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Ster','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Stormia','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲STR+1','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲STR+2','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲STR+3','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Tarna','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Teo','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲the emptiness of forgetfulness','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲the shadow of the wandering','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Theru','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Theru II','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲transparent Christa','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲trial of rock','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Tsuchinoko King','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Valtia','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Vasaria','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Vatendeth','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Veltria','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Vida','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲VIT+1','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲VIT+2','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲VIT+3','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Vulschem','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Warrior of Light','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲white sun flash','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Wilnes','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Zazel','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'▲Zolte','AlCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□10th Anniversary','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□AGI+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□AGI+2','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□AGI+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Alchemy Success +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Altern','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Angenger','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Arick','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+5','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+7','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ATK+9','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Aufsea','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Blaiard','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Blauzen','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Bleed Damage +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Bleed Damage +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Bleed Damage +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Bubbly Hat','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Bubbly Love','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Burn Damage +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Burn Damage +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Burn Damage +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Callecra','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Carpentry Success +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Cast Time -1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Cast Time -2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Cast Time -3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Chasing Success +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Cooking Success +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Cordal','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□CRT+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□CRT+2','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□CRT+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Dark Magic +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Dark Magic +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Dark Magic +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Debby','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□DEX+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□DEX+2','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□DEX+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Drop Rate +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Drop Rate +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Drop Rate +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Earth Magic +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Earth Magic +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Earth Magic +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Easter Egg','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Eilena','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Eisen','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□EXP Gain +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□EXP Gain +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□EXP Gain +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Faded Dark Memory','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Faded Earth Memory','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Faded Fire Memory','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Faded Light Memory','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Faded Water Memory','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Faded Wind Memory','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Fire Magic +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Fire Magic +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Fire Magic +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Giant Colon','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Giorgio','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Hate Rise -1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Hate Rise -2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Hate Rise -3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Hate Rise +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Hate Rise +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Hate Rise +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Heal Recovery +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Heal Recovery +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Heal Recovery +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Heal Reward +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Heal Reward +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Heal Reward +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□INT+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□INT+2','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□INT+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Jinami','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Light Magic +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Light Magic +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Light Magic +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic +150','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic +200','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic +250','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic +300','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic Pierce +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic Pierce +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic Pierce +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic+1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Magic+100','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+5','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+7','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MATK+9','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxHP+1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxHP+100','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxHP+2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXHP+200','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxHP+3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXHP+300','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXHP+400','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXHP+500','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxMP+1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXMP+100','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxMP+2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxMP+20','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MaxMP+3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXMP+40','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXMP+60','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MAXMP+80','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee +150','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee +200','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee +250','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee +300','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee Pierce +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee Pierce +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee Pierce +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+1% to Dark','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+1% to Earth','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+1% to Fire','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+1% to Light','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+1% to Water','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+1% to Wind','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+100','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+2% to Dark','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+2% to Earth','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+2% to Fire','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+2% to Light','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+2% to Water','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+2% to Wind','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+3% to Dark','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+3% to Earth','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+3% to Fire','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+3% to Light','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+3% to Water','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Melee+3% to Wind','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Memory Fragment','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Metal Sauro','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Mish','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MP Cost -1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MP Cost -2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□MP Cost -3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Nejua','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Oswald','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Poison +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Poison +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Poison+1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Rainbow Trail','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Rita','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Rowell','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Roy','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Smith Success +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□STR+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□STR+2','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□STR+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Tailoring Success +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Transformation Trail','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Trashiddoh','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Uradoom','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Vapawr','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Vida','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□VIT+1','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□VIT+2','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□VIT+3','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Warrior''s Jewelry','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Water Magic +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Water Magic +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Water Magic +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Wind Magic +1%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Wind Magic +2%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□Wind Magic +3%','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□エリザベス','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□キゲンデ','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□キング','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ディアンヌ','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□バン','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ホーク','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□ホロウアクス','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□マーリン','RelicCrystas');
INSERT INTO `irunaitem` VALUES(NULL,'□メリオダス','RelicCrystas');
COMMIT;
